// Auto-generated by lele_compiler
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
use lele::tensor::TensorView;
use lele::kernels::*;


#[derive(Default)]
pub struct Yolo26SegWorkspace {
    pub buf_0: Vec<f32>,
    pub buf_1: Vec<f32>,
    pub buf_2: Vec<f32>,
    pub buf_3: Vec<f32>,
    pub buf_4: Vec<f32>,
    pub buf_5: Vec<f32>,
    pub buf_6: Vec<f32>,
    pub buf_7: Vec<f32>,
    pub buf_8: Vec<f32>,
    pub buf_9: Vec<f32>,
    pub buf_10: Vec<f32>,
    pub buf_11: Vec<f32>,
    pub buf_12: Vec<f32>,
    pub buf_13: Vec<f32>,
    pub buf_14: Vec<f32>,
    pub buf_15: Vec<f32>,
    pub buf_16: Vec<f32>,
    pub buf_17: Vec<f32>,
    pub buf_18: Vec<f32>,
    pub buf_19: Vec<f32>,
    pub buf_20: Vec<f32>,
}
impl Yolo26SegWorkspace {
    pub fn new() -> Self {
        Self::default()
    }
}

pub struct Yolo26Seg<'a> {
    data: &'a [u8],
    _phantom: std::marker::PhantomData<&'a ()>,
    #[cfg(target_arch = "aarch64")]
    prepared_weights_cache: std::cell::RefCell<std::collections::HashMap<(usize, usize), std::sync::Arc<lele::kernels::PreparedWeightsArm>>>,
}

impl<'a> Yolo26Seg<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            _phantom: std::marker::PhantomData,
            #[cfg(target_arch = "aarch64")]
            prepared_weights_cache: std::cell::RefCell::new(std::collections::HashMap::new()),
        }
    }
fn conv1d_relu<'c, 'd>(
    &self,
    input: lele::tensor::TensorView<'c>,
    weight: lele::tensor::TensorView<'c>,
    bias: Option<&lele::tensor::TensorView<'c>>,
    stride: usize,
    dilation: usize,
    groups: usize,
    padding: usize,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::conv1d_fused(
        &input,
        &weight,
        bias,
        &[dilation as i64],
        groups as i64,
        &[padding as i64, padding as i64],
        &[stride as i64],
        true,
        output_buf,
    )
}
fn layer_norm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    scale: lele::tensor::TensorView<'c>,
    bias: lele::tensor::TensorView<'c>,
    epsilon: lele::tensor::TensorView<'c>,
    _two: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    let eps = epsilon.data.first().cloned().unwrap_or(1e-5);
    lele::kernels::layer_norm(input, &scale, &bias, -1, eps, output_buf)
}
fn linear_quantized<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, false, output_buf,
    )
}

fn linear_quantized_relu<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, true, output_buf,
    )
}

#[cfg(target_arch = "aarch64")]
fn linear_quantized_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        false,
        output_buf,
    )
}

/// ARM-optimized quantized linear + ReLU with pre-packed weights.
/// Uses fused DynQuant+GEMM: eliminates f32 intermediate buffer, per-call u8
/// allocation, and separate f32→u8 conversion pass.
#[cfg(target_arch = "aarch64")]
fn linear_quantized_relu_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        true,
        output_buf,
    )
}

/// ARM-optimized MatMulInteger with pre-packed weight cache.
/// Used for unfused MatMulInteger nodes where B is a static model weight.
/// Eliminates: per-call B packing, B u8→f32→u8 roundtrip, heap alloc.
#[cfg(target_arch = "aarch64")]
fn mat_mul_integer_arm<'c, 'd>(
    &self,
    a: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    a_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    b_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_a = a_zero_point.and_then(|z| z.data.first().cloned());
    let zp_b = b_zero_point.and_then(|z| z.data.first()).map(|&v| v as u8);

    lele::kernels::mat_mul_integer_prepared_arm(a, &pw, zp_a, zp_b, None, None, false, output_buf)
}

// Helper for pre-quantized inputs (used in attention where input is already quantized)
#[inline]
fn linear_quantized_prequant<'c, 'd>(
    &self,
    input_quantized: &lele::tensor::TensorView<'c, f32>,
    input_scale: &lele::tensor::TensorView<'c, f32>,
    input_zero_point: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
    scale_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let combined_scale = lele::kernels::mul(input_scale, &weight_scale, scale_buf);

    // FUSED: MatMul + Scale + Bias in one operation
    lele::kernels::mat_mul_integer_with_scale_bias(
        input_quantized,
        &weight_int8,
        Some(input_zero_point),
        Some(&weight_zero),
        Some(&combined_scale),
        Some(&bias),
        output_buf,
    )
}
fn linear<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    weight: &lele::tensor::TensorView<'c>,
    bias: &lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::matmul_fused_add(input, weight, bias, output_buf)
}

fn embedding_concat<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: f32,
    weight: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    // ConstantOfShape + Concat pattern
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

fn embedding_concat_i64<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: i64,
    weight: lele::tensor::TensorView<'c, i64>,
    output_buf: &'d mut Vec<i64>,
) -> lele::tensor::TensorView<'d, i64> {
    // ConstantOfShape + Concat pattern (i64)
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

    #[inline(never)]
    fn run_chunk_0<'w>(&self, ws: &'w mut Yolo26SegWorkspace, images: TensorView<'w, f32>) -> (TensorView<'static, f32>, TensorView<'static, f32>) {
        let _model_0_act_Mul_output_0 = lele::kernels::conv2d_silu(&images, &self.weight_f32(0, 1728, &[16, 3, 3, 3]), Some(&self.weight_f32(1728, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_2);
        let _model_1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_0_act_Mul_output_0, &self.weight_f32(1792, 18432, &[32, 16, 3, 3]), Some(&self.weight_f32(20224, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_5);
        let _model_2_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_1_act_Mul_output_0, &self.weight_f32(20352, 4096, &[32, 32, 1, 1]), Some(&self.weight_f32(24448, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let splits_slice = &[16, 16];
        let mut split_results = lele::kernels::split_owned(&_model_2_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_2_Split_output_1 = split_results.swap_remove(1);
        let _model_2_Split_output_0 = split_results.swap_remove(0);
        let _model_2_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_2_Split_output_1, &self.weight_f32(24592, 4608, &[8, 16, 3, 3]), Some(&self.weight_f32(29200, 32, &[8])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _model_2_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_2_m_0_cv1_act_Mul_output_0, &self.weight_f32(29232, 4608, &[16, 8, 3, 3]), Some(&self.weight_f32(33840, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_0);
        let _model_2_m_0_Add_output_0 = lele::kernels::add(&_model_2_Split_output_1, &_model_2_m_0_cv2_act_Mul_output_0, &mut ws.buf_7);
        let _model_2_Concat_output_0 = lele::kernels::concat(&[&_model_2_Split_output_0, &_model_2_Split_output_1, &_model_2_m_0_Add_output_0], 1, &mut ws.buf_9);
        let _model_2_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_2_Concat_output_0, &self.weight_f32(33904, 12288, &[64, 48, 1, 1]), Some(&self.weight_f32(46192, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _model_3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_2_cv2_act_Mul_output_0, &self.weight_f32(46448, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(193904, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _model_4_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_3_act_Mul_output_0, &self.weight_f32(194160, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(210544, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let splits_slice = &[32, 32];
        let mut split_results = lele::kernels::split_owned(&_model_4_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_4_Split_output_1 = split_results.swap_remove(1);
        let _model_4_Split_output_0 = split_results.swap_remove(0);
        let _model_4_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_4_Split_output_1, &self.weight_f32(210816, 18432, &[16, 32, 3, 3]), Some(&self.weight_f32(229248, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let _model_4_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_4_m_0_cv1_act_Mul_output_0, &self.weight_f32(229312, 18432, &[32, 16, 3, 3]), Some(&self.weight_f32(247744, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _model_4_m_0_Add_output_0 = lele::kernels::add(&_model_4_Split_output_1, &_model_4_m_0_cv2_act_Mul_output_0, &mut ws.buf_6);
        let _model_4_Concat_output_0 = lele::kernels::concat(&[&_model_4_Split_output_0, &_model_4_Split_output_1, &_model_4_m_0_Add_output_0], 1, &mut ws.buf_9);
        let _model_4_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_4_Concat_output_0, &self.weight_f32(247872, 49152, &[128, 96, 1, 1]), Some(&self.weight_f32(297024, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _model_5_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_4_cv2_act_Mul_output_0, &self.weight_f32(297536, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(887360, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_4);
        let _model_6_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_5_act_Mul_output_0, &self.weight_f32(887872, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(953408, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let splits_slice = &[64, 64];
        let mut split_results = lele::kernels::split_owned(&_model_6_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_6_Split_output_1 = split_results.swap_remove(1);
        let _model_6_Split_output_0 = split_results.swap_remove(0);
        let _model_6_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_6_Split_output_1, &self.weight_f32(953936, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(962128, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_9);
        let _model_6_m_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_6_Split_output_1, &self.weight_f32(962256, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(970448, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let _model_6_m_0_cv1_act_Mul_output_0 = lele::kernels::silu(&_model_6_m_0_cv1_conv_Conv_output_0, &mut ws.buf_5);
        let _model_6_m_0_cv2_act_Mul_output_0 = lele::kernels::silu(&_model_6_m_0_cv2_conv_Conv_output_0, &mut ws.buf_0);
        let _model_6_m_0_m_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_m_0_cv1_act_Mul_output_0, &self.weight_f32(970576, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(1007440, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_11);
        let _model_6_m_0_m_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_m_0_m_m_0_cv1_act_Mul_output_0, &self.weight_f32(1007568, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(1044432, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _model_6_m_0_m_m_0_Add_output_0 = lele::kernels::add(&_model_6_m_0_cv1_act_Mul_output_0, &_model_6_m_0_m_m_0_cv2_act_Mul_output_0, &mut ws.buf_4);
        let _model_6_m_0_m_m_1_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_m_0_m_m_0_Add_output_0, &self.weight_f32(1044560, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(1081424, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_10);
        let _model_6_m_0_m_m_1_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_m_0_m_m_1_cv1_act_Mul_output_0, &self.weight_f32(1081552, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(1118416, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _model_6_m_0_m_m_1_Add_output_0 = lele::kernels::add(&_model_6_m_0_m_m_0_Add_output_0, &_model_6_m_0_m_m_1_cv2_act_Mul_output_0, &mut ws.buf_5);
        let _model_6_m_0_Concat_output_0 = lele::kernels::concat(&[&_model_6_m_0_m_m_1_Add_output_0, &_model_6_m_0_cv2_act_Mul_output_0], 1, &mut ws.buf_12);
        let _model_6_m_0_cv3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_m_0_Concat_output_0, &self.weight_f32(1118544, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(1134928, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _model_6_Concat_output_0 = lele::kernels::concat(&[&_model_6_Split_output_0, &_model_6_Split_output_1, &_model_6_m_0_cv3_act_Mul_output_0], 1, &mut ws.buf_3);
        let _model_6_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_Concat_output_0, &self.weight_f32(1135184, 98304, &[128, 192, 1, 1]), Some(&self.weight_f32(1233488, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let _model_7_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_6_cv2_act_Mul_output_0, &self.weight_f32(1234000, 1179648, &[256, 128, 3, 3]), Some(&self.weight_f32(2413648, 1024, &[256])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_1);
        let _model_8_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_7_act_Mul_output_0, &self.weight_f32(2414672, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(2676816, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let splits_slice = &[128, 128];
        let mut split_results = lele::kernels::split_owned(&_model_8_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_8_Split_output_1 = split_results.swap_remove(1);
        let _model_8_Split_output_0 = split_results.swap_remove(0);
        let _model_8_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_8_Split_output_1, &self.weight_f32(2677856, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(2710624, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _model_8_m_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_8_Split_output_1, &self.weight_f32(2710880, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(2743648, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_8_m_0_cv1_act_Mul_output_0 = lele::kernels::silu(&_model_8_m_0_cv1_conv_Conv_output_0, &mut ws.buf_3);
        let _model_8_m_0_cv2_act_Mul_output_0 = lele::kernels::silu(&_model_8_m_0_cv2_conv_Conv_output_0, &mut ws.buf_0);
        let _model_8_m_0_m_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_m_0_cv1_act_Mul_output_0, &self.weight_f32(2743904, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(2891360, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_12);
        let _model_8_m_0_m_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_m_0_m_m_0_cv1_act_Mul_output_0, &self.weight_f32(2891616, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(3039072, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let _model_8_m_0_m_m_0_Add_output_0 = lele::kernels::add(&_model_8_m_0_cv1_act_Mul_output_0, &_model_8_m_0_m_m_0_cv2_act_Mul_output_0, &mut ws.buf_6);
        let _model_8_m_0_m_m_1_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_m_0_m_m_0_Add_output_0, &self.weight_f32(3039328, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(3186784, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_11);
        let _model_8_m_0_m_m_1_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_m_0_m_m_1_cv1_act_Mul_output_0, &self.weight_f32(3187040, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(3334496, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _model_8_m_0_m_m_1_Add_output_0 = lele::kernels::add(&_model_8_m_0_m_m_0_Add_output_0, &_model_8_m_0_m_m_1_cv2_act_Mul_output_0, &mut ws.buf_5);
        let _model_8_m_0_Concat_output_0 = lele::kernels::concat(&[&_model_8_m_0_m_m_1_Add_output_0, &_model_8_m_0_cv2_act_Mul_output_0], 1, &mut ws.buf_13);
        let _model_8_m_0_cv3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_m_0_Concat_output_0, &self.weight_f32(3334752, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(3400288, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _model_8_Concat_output_0 = lele::kernels::concat(&[&_model_8_Split_output_0, &_model_8_Split_output_1, &_model_8_m_0_cv3_act_Mul_output_0], 1, &mut ws.buf_1);
        let _model_8_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_8_Concat_output_0, &self.weight_f32(3400800, 393216, &[256, 384, 1, 1]), Some(&self.weight_f32(3794016, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_9_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_8_cv2_act_Mul_output_0, &self.weight_f32(3795040, 131072, &[128, 256, 1, 1]), Some(&self.weight_f32(3926112, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_9_m_MaxPool_output_0 = lele::kernels::max_pool2d(&_model_9_cv1_conv_Conv_output_0, &[5, 5], &[1, 1], &[2, 2, 2, 2], &[1, 1], false, &mut ws.buf_7);
        let _model_9_m_1_MaxPool_output_0 = lele::kernels::max_pool2d(&_model_9_m_MaxPool_output_0, &[5, 5], &[1, 1], &[2, 2, 2, 2], &[1, 1], false, &mut ws.buf_2);
        let _model_9_m_2_MaxPool_output_0 = lele::kernels::max_pool2d(&_model_9_m_1_MaxPool_output_0, &[5, 5], &[1, 1], &[2, 2, 2, 2], &[1, 1], false, &mut ws.buf_1);
        let _model_9_Concat_output_0 = lele::kernels::concat(&[&_model_9_cv1_conv_Conv_output_0, &_model_9_m_MaxPool_output_0, &_model_9_m_1_MaxPool_output_0, &_model_9_m_2_MaxPool_output_0], 1, &mut ws.buf_9);
        let _model_9_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_9_Concat_output_0, &self.weight_f32(3926624, 524288, &[256, 512, 1, 1]), Some(&self.weight_f32(4450912, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _model_9_Add_output_0 = lele::kernels::add(&_model_9_cv2_act_Mul_output_0, &_model_8_cv2_act_Mul_output_0, &mut ws.buf_11);
        let _model_10_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_9_Add_output_0, &self.weight_f32(4451936, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(4714080, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let splits_slice = &[128, 128];
        let mut split_results = lele::kernels::split_owned(&_model_10_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_10_Split_output_1 = split_results.swap_remove(1);
        let _model_10_Split_output_0 = split_results.swap_remove(0);
        let _model_10_m_m_0_attn_qkv_conv_Conv_output_0 = lele::kernels::conv2d(&_model_10_Split_output_1, &self.weight_f32(4715104, 131072, &[256, 128, 1, 1]), Some(&self.weight_f32(4846176, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let _model_10_m_m_0_attn_Reshape_output_0 = lele::kernels::reshape(&_model_10_m_m_0_attn_qkv_conv_Conv_output_0, &[1, 2, 128, 400]);
        let splits_slice = &[32, 32, 64];
        let mut split_results = lele::kernels::split_owned(&_model_10_m_m_0_attn_Reshape_output_0, 2, splits_slice);
        let _model_10_m_m_0_attn_Split_output_2 = split_results.swap_remove(2);
        let _model_10_m_m_0_attn_Split_output_1 = split_results.swap_remove(1);
        let _model_10_m_m_0_attn_Split_output_0 = split_results.swap_remove(0);
        let _model_10_m_m_0_attn_Transpose_output_0 = lele::kernels::transpose(&_model_10_m_m_0_attn_Split_output_0, &[0, 1, 3, 2], &mut ws.buf_10);
        let _model_10_m_m_0_attn_Reshape_2_output_0 = lele::kernels::reshape(&_model_10_m_m_0_attn_Split_output_2, &[1, 128, 20, 20]);
        let _model_10_m_m_0_attn_MatMul_output_0 = lele::kernels::matmul(&_model_10_m_m_0_attn_Transpose_output_0, &_model_10_m_m_0_attn_Split_output_1, &mut ws.buf_1);
        let _model_10_m_m_0_attn_pe_conv_Conv_output_0 = lele::kernels::conv2d(&_model_10_m_m_0_attn_Reshape_2_output_0, &self.weight_f32(4847296, 4608, &[128, 1, 3, 3]), Some(&self.weight_f32(4851904, 512, &[128])), &[1, 1], 128, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _model_10_m_m_0_attn_Mul_output_0 = lele::kernels::mul(&_model_10_m_m_0_attn_MatMul_output_0, &self.weight_f32(4852416, 4, &[]), &mut ws.buf_11);
        let _model_10_m_m_0_attn_Softmax_output_0 = lele::kernels::softmax(&_model_10_m_m_0_attn_Mul_output_0, -1, &mut ws.buf_0);
        let _model_10_m_m_0_attn_Transpose_1_output_0 = lele::kernels::transpose(&_model_10_m_m_0_attn_Softmax_output_0, &[0, 1, 3, 2], &mut ws.buf_3);
        let _model_10_m_m_0_attn_MatMul_1_output_0 = lele::kernels::matmul(&_model_10_m_m_0_attn_Split_output_2, &_model_10_m_m_0_attn_Transpose_1_output_0, &mut ws.buf_12);
        let _model_10_m_m_0_attn_Reshape_1_output_0 = lele::kernels::reshape(&_model_10_m_m_0_attn_MatMul_1_output_0, &[1, 128, 20, 20]);
        let _model_10_m_m_0_attn_Add_output_0 = lele::kernels::add(&_model_10_m_m_0_attn_Reshape_1_output_0, &_model_10_m_m_0_attn_pe_conv_Conv_output_0, &mut ws.buf_5);
        let _model_10_m_m_0_attn_proj_conv_Conv_output_0 = lele::kernels::conv2d(&_model_10_m_m_0_attn_Add_output_0, &self.weight_f32(4852432, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(4917968, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let _model_10_m_m_0_Add_output_0 = lele::kernels::add(&_model_10_Split_output_1, &_model_10_m_m_0_attn_proj_conv_Conv_output_0, &mut ws.buf_10);
        let _model_10_m_m_0_ffn_ffn_0_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_10_m_m_0_Add_output_0, &self.weight_f32(4918480, 131072, &[256, 128, 1, 1]), Some(&self.weight_f32(5049552, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_9);
        let _model_10_m_m_0_ffn_ffn_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_10_m_m_0_ffn_ffn_0_act_Mul_output_0, &self.weight_f32(5050576, 131072, &[128, 256, 1, 1]), Some(&self.weight_f32(5181648, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let _model_10_m_m_0_Add_1_output_0 = lele::kernels::add(&_model_10_m_m_0_Add_output_0, &_model_10_m_m_0_ffn_ffn_1_conv_Conv_output_0, &mut ws.buf_5);
        let _model_10_Concat_output_0 = lele::kernels::concat(&[&_model_10_Split_output_0, &_model_10_m_m_0_Add_1_output_0], 1, &mut ws.buf_1);
        let _model_10_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_10_Concat_output_0, &self.weight_f32(5182160, 262144, &[256, 256, 1, 1]), Some(&self.weight_f32(5444304, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let _model_11_Resize_output_0 = lele::kernels::resize_nearest(&_model_10_cv2_act_Mul_output_0, Some(&self.weight_f32(5445328, 16, &[4]).data), None, "asymmetric", &mut ws.buf_3);
        let _model_12_Concat_output_0 = lele::kernels::concat(&[&_model_11_Resize_output_0, &_model_6_cv2_act_Mul_output_0], 1, &mut ws.buf_2);
        let _model_13_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_12_Concat_output_0, &self.weight_f32(5445344, 196608, &[128, 384, 1, 1]), Some(&self.weight_f32(5641952, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let splits_slice = &[64, 64];
        let mut split_results = lele::kernels::split_owned(&_model_13_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_13_Split_output_1 = split_results.swap_remove(1);
        let _model_13_Split_output_0 = split_results.swap_remove(0);
        let _model_13_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_13_Split_output_1, &self.weight_f32(5642464, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(5650656, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _model_13_m_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_13_Split_output_1, &self.weight_f32(5650784, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(5658976, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let _model_13_m_0_cv1_act_Mul_output_0 = lele::kernels::silu(&_model_13_m_0_cv1_conv_Conv_output_0, &mut ws.buf_1);
        let _model_13_m_0_cv2_act_Mul_output_0 = lele::kernels::silu(&_model_13_m_0_cv2_conv_Conv_output_0, &mut ws.buf_5);
        let _model_13_m_0_m_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_m_0_cv1_act_Mul_output_0, &self.weight_f32(5659104, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(5695968, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_12);
        let _model_13_m_0_m_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_m_0_m_m_0_cv1_act_Mul_output_0, &self.weight_f32(5696096, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(5732960, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _model_13_m_0_m_m_0_Add_output_0 = lele::kernels::add(&_model_13_m_0_cv1_act_Mul_output_0, &_model_13_m_0_m_m_0_cv2_act_Mul_output_0, &mut ws.buf_4);
        let _model_13_m_0_m_m_1_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_m_0_m_m_0_Add_output_0, &self.weight_f32(5733088, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(5769952, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_11);
        let _model_13_m_0_m_m_1_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_m_0_m_m_1_cv1_act_Mul_output_0, &self.weight_f32(5770080, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(5806944, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let _model_13_m_0_m_m_1_Add_output_0 = lele::kernels::add(&_model_13_m_0_m_m_0_Add_output_0, &_model_13_m_0_m_m_1_cv2_act_Mul_output_0, &mut ws.buf_3);
        let _model_13_m_0_Concat_output_0 = lele::kernels::concat(&[&_model_13_m_0_m_m_1_Add_output_0, &_model_13_m_0_cv2_act_Mul_output_0], 1, &mut ws.buf_13);
        let _model_13_m_0_cv3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_m_0_Concat_output_0, &self.weight_f32(5807072, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(5823456, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _model_13_Concat_output_0 = lele::kernels::concat(&[&_model_13_Split_output_0, &_model_13_Split_output_1, &_model_13_m_0_cv3_act_Mul_output_0], 1, &mut ws.buf_2);
        let _model_13_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_13_Concat_output_0, &self.weight_f32(5823712, 98304, &[128, 192, 1, 1]), Some(&self.weight_f32(5922016, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let _model_14_Resize_output_0 = lele::kernels::resize_nearest(&_model_13_cv2_act_Mul_output_0, Some(&self.weight_f32(5445328, 16, &[4]).data), None, "asymmetric", &mut ws.buf_5);
        let _model_15_Concat_output_0 = lele::kernels::concat(&[&_model_14_Resize_output_0, &_model_4_cv2_act_Mul_output_0], 1, &mut ws.buf_6);
        let _model_16_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_15_Concat_output_0, &self.weight_f32(5922528, 65536, &[64, 256, 1, 1]), Some(&self.weight_f32(5988064, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_9);
        let splits_slice = &[32, 32];
        let mut split_results = lele::kernels::split_owned(&_model_16_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_16_Split_output_1 = split_results.swap_remove(1);
        let _model_16_Split_output_0 = split_results.swap_remove(0);
        let _model_16_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_Split_output_1, &self.weight_f32(5988320, 2048, &[16, 32, 1, 1]), Some(&self.weight_f32(5990368, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_10);
        let _model_16_m_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_Split_output_1, &self.weight_f32(5990432, 2048, &[16, 32, 1, 1]), Some(&self.weight_f32(5992480, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_16_m_0_cv1_act_Mul_output_0 = lele::kernels::silu(&_model_16_m_0_cv1_conv_Conv_output_0, &mut ws.buf_2);
        let _model_16_m_0_cv2_act_Mul_output_0 = lele::kernels::silu(&_model_16_m_0_cv2_conv_Conv_output_0, &mut ws.buf_7);
        let _model_16_m_0_m_m_0_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_m_0_cv1_act_Mul_output_0, &self.weight_f32(5992544, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(6001760, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_12);
        let _model_16_m_0_m_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_m_0_m_m_0_cv1_act_Mul_output_0, &self.weight_f32(6001824, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(6011040, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let _model_16_m_0_m_m_0_Add_output_0 = lele::kernels::add(&_model_16_m_0_cv1_act_Mul_output_0, &_model_16_m_0_m_m_0_cv2_act_Mul_output_0, &mut ws.buf_8);
        let _model_16_m_0_m_m_1_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_m_0_m_m_0_Add_output_0, &self.weight_f32(6011104, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(6020320, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_11);
        let _model_16_m_0_m_m_1_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_m_0_m_m_1_cv1_act_Mul_output_0, &self.weight_f32(6020384, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(6029600, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _model_16_m_0_m_m_1_Add_output_0 = lele::kernels::add(&_model_16_m_0_m_m_0_Add_output_0, &_model_16_m_0_m_m_1_cv2_act_Mul_output_0, &mut ws.buf_5);
        let _model_16_m_0_Concat_output_0 = lele::kernels::concat(&[&_model_16_m_0_m_m_1_Add_output_0, &_model_16_m_0_cv2_act_Mul_output_0], 1, &mut ws.buf_13);
        let _model_16_m_0_cv3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_m_0_Concat_output_0, &self.weight_f32(6029664, 4096, &[32, 32, 1, 1]), Some(&self.weight_f32(6033760, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _model_16_Concat_output_0 = lele::kernels::concat(&[&_model_16_Split_output_0, &_model_16_Split_output_1, &_model_16_m_0_cv3_act_Mul_output_0], 1, &mut ws.buf_6);
        let _model_16_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_16_Concat_output_0, &self.weight_f32(6033888, 24576, &[64, 96, 1, 1]), Some(&self.weight_f32(6058464, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let _model_17_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_cv2_act_Mul_output_0, &self.weight_f32(6058720, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(6206176, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_8);
        let _model_23_one2one_cv2_0_one2one_cv2_0_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_cv2_act_Mul_output_0, &self.weight_f32(6206432, 36864, &[16, 64, 3, 3]), Some(&self.weight_f32(6243296, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_cv2_act_Mul_output_0, &self.weight_f32(6243360, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(6245664, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let _model_23_one2one_cv4_0_one2one_cv4_0_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_16_cv2_act_Mul_output_0, &self.weight_f32(6245920, 73728, &[32, 64, 3, 3]), Some(&self.weight_f32(6319648, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let _model_17_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_17_conv_Conv_output_0, &mut ws.buf_6);
        let _model_23_one2one_cv2_0_one2one_cv2_0_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_0_one2one_cv2_0_0_conv_Conv_output_0, &mut ws.buf_2);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_conv_Conv_output_0, &mut ws.buf_5);
        let _model_23_one2one_cv4_0_one2one_cv4_0_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_0_one2one_cv4_0_0_conv_Conv_output_0, &mut ws.buf_10);
        let _model_17_act_Mul_output_0 = lele::kernels::mul(&_model_17_conv_Conv_output_0, &_model_17_act_Sigmoid_output_0, &mut ws.buf_11);
        let _model_23_one2one_cv2_0_one2one_cv2_0_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_0_one2one_cv2_0_0_conv_Conv_output_0, &_model_23_one2one_cv2_0_one2one_cv2_0_0_act_Sigmoid_output_0, &mut ws.buf_12);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_conv_Conv_output_0, &_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_act_Sigmoid_output_0, &mut ws.buf_13);
        let _model_23_one2one_cv4_0_one2one_cv4_0_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_0_one2one_cv4_0_0_conv_Conv_output_0, &_model_23_one2one_cv4_0_one2one_cv4_0_0_act_Sigmoid_output_0, &mut ws.buf_14);
        let _model_18_Concat_output_0 = lele::kernels::concat(&[&_model_17_act_Mul_output_0, &_model_13_cv2_act_Mul_output_0], 1, &mut ws.buf_15);
        let _model_23_one2one_cv2_0_one2one_cv2_0_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_0_one2one_cv2_0_0_act_Mul_output_0, &self.weight_f32(6319776, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(6328992, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_16);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_0_act_Mul_output_0, &self.weight_f32(6329056, 20480, &[80, 64, 1, 1]), Some(&self.weight_f32(6349536, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_23_one2one_cv4_0_one2one_cv4_0_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_0_one2one_cv4_0_0_act_Mul_output_0, &self.weight_f32(6349856, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(6386720, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let _model_19_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_18_Concat_output_0, &self.weight_f32(6386848, 98304, &[128, 192, 1, 1]), Some(&self.weight_f32(6485152, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let _model_23_one2one_cv2_0_one2one_cv2_0_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_0_one2one_cv2_0_1_conv_Conv_output_0, &mut ws.buf_3);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_conv_Conv_output_0, &mut ws.buf_4);
        let _model_23_one2one_cv4_0_one2one_cv4_0_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_0_one2one_cv4_0_1_conv_Conv_output_0, &mut ws.buf_5);
        let _model_19_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_19_cv1_conv_Conv_output_0, &mut ws.buf_8);
        let _model_23_one2one_cv2_0_one2one_cv2_0_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_0_one2one_cv2_0_1_conv_Conv_output_0, &_model_23_one2one_cv2_0_one2one_cv2_0_1_act_Sigmoid_output_0, &mut ws.buf_9);
        let _model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_conv_Conv_output_0, &_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_act_Sigmoid_output_0, &mut ws.buf_10);
        let _model_23_one2one_cv4_0_one2one_cv4_0_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_0_one2one_cv4_0_1_conv_Conv_output_0, &_model_23_one2one_cv4_0_one2one_cv4_0_1_act_Sigmoid_output_0, &mut ws.buf_11);
        let _model_19_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_19_cv1_conv_Conv_output_0, &_model_19_cv1_act_Sigmoid_output_0, &mut ws.buf_12);
        let _model_23_one2one_cv2_0_one2one_cv2_0_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_0_one2one_cv2_0_1_act_Mul_output_0, &self.weight_f32(6485664, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(6485920, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_13);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_0_one2one_cv3_0_0_one2one_cv3_0_0_1_act_Mul_output_0, &self.weight_f32(6485936, 2880, &[80, 1, 3, 3]), Some(&self.weight_f32(6488816, 320, &[80])), &[1, 1], 80, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_14);
        let _model_23_one2one_cv4_0_one2one_cv4_0_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_0_one2one_cv4_0_1_act_Mul_output_0, &self.weight_f32(6489136, 4096, &[32, 32, 1, 1]), Some(&self.weight_f32(6493232, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let splits_slice = &[64, 64];
        let mut split_results = lele::kernels::split_owned(&_model_19_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_19_Split_output_1 = split_results.swap_remove(1);
        let _model_19_Split_output_0 = split_results.swap_remove(0);
        let _model_23_Reshape_output_0 = lele::kernels::reshape(&_model_23_one2one_cv2_0_one2one_cv2_0_2_Conv_output_0, &[1, 4, -1]);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_conv_Conv_output_0, &mut ws.buf_1);
        let _model_23_Reshape_6_output_0 = lele::kernels::reshape(&_model_23_one2one_cv4_0_one2one_cv4_0_2_Conv_output_0, &[1, 32, -1]);
        let _model_19_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_Split_output_1, &self.weight_f32(6493424, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(6501616, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let _model_19_m_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_Split_output_1, &self.weight_f32(6501744, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(6509936, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_conv_Conv_output_0, &_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_act_Sigmoid_output_0, &mut ws.buf_8);
        let _model_19_m_0_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_19_m_0_cv1_conv_Conv_output_0, &mut ws.buf_9);
        let _model_19_m_0_cv2_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_19_m_0_cv2_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_0_act_Mul_output_0, &self.weight_f32(6510064, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(6535664, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _model_19_m_0_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_19_m_0_cv1_conv_Conv_output_0, &_model_19_m_0_cv1_act_Sigmoid_output_0, &mut ws.buf_12);
        let _model_19_m_0_cv2_act_Mul_output_0 = lele::kernels::mul(&_model_19_m_0_cv2_conv_Conv_output_0, &_model_19_m_0_cv2_act_Sigmoid_output_0, &mut ws.buf_15);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_conv_Conv_output_0, &mut ws.buf_1);
        let _model_19_m_0_m_m_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_m_0_cv1_act_Mul_output_0, &self.weight_f32(6535984, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(6572848, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_14);
        let _model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_conv_Conv_output_0, &_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_act_Sigmoid_output_0, &mut ws.buf_16);
        let _model_19_m_0_m_m_0_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_19_m_0_m_m_0_cv1_conv_Conv_output_0, &mut ws.buf_8);
        let _model_23_one2one_cv3_0_one2one_cv3_0_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_0_one2one_cv3_0_1_one2one_cv3_0_1_1_act_Mul_output_0, &self.weight_f32(6572976, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(6598576, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let _model_19_m_0_m_m_0_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_19_m_0_m_m_0_cv1_conv_Conv_output_0, &_model_19_m_0_m_m_0_cv1_act_Sigmoid_output_0, &mut ws.buf_5);
        let _model_23_Reshape_3_output_0 = lele::kernels::reshape(&_model_23_one2one_cv3_0_one2one_cv3_0_2_Conv_output_0, &[1, 80, -1]);
        let _model_19_m_0_m_m_0_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_19_m_0_m_m_0_cv1_act_Mul_output_0, &self.weight_f32(6598928, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(6635792, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_10);
        let _model_19_m_0_m_m_0_Add_output_0 = lele::kernels::add(&_model_19_m_0_cv1_act_Mul_output_0, &_model_19_m_0_m_m_0_cv2_act_Mul_output_0, &mut ws.buf_11);
        let _model_19_m_0_m_m_1_cv1_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_19_m_0_m_m_0_Add_output_0, &self.weight_f32(6635920, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(6672784, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let _model_19_m_0_m_m_1_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_19_m_0_m_m_1_cv1_act_Mul_output_0, &self.weight_f32(6672912, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(6709776, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_9);
        let _model_19_m_0_m_m_1_Add_output_0 = lele::kernels::add(&_model_19_m_0_m_m_0_Add_output_0, &_model_19_m_0_m_m_1_cv2_act_Mul_output_0, &mut ws.buf_10);
        let _model_19_m_0_Concat_output_0 = lele::kernels::concat(&[&_model_19_m_0_m_m_1_Add_output_0, &_model_19_m_0_cv2_act_Mul_output_0], 1, &mut ws.buf_12);
        let _model_19_m_0_cv3_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_19_m_0_Concat_output_0, &self.weight_f32(6709904, 16384, &[64, 64, 1, 1]), Some(&self.weight_f32(6726288, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_14);
        let _model_19_Concat_output_0 = lele::kernels::concat(&[&_model_19_Split_output_0, &_model_19_Split_output_1, &_model_19_m_0_cv3_act_Mul_output_0], 1, &mut ws.buf_1);
        let _model_19_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_19_Concat_output_0, &self.weight_f32(6726544, 98304, &[128, 192, 1, 1]), Some(&self.weight_f32(6824848, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_11);
        let _model_20_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_cv2_act_Mul_output_0, &self.weight_f32(6825360, 589824, &[128, 128, 3, 3]), Some(&self.weight_f32(7415184, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_12);
        let _model_23_one2one_cv2_1_one2one_cv2_1_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_cv2_act_Mul_output_0, &self.weight_f32(7415696, 73728, &[16, 128, 3, 3]), Some(&self.weight_f32(7489424, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_cv2_act_Mul_output_0, &self.weight_f32(7489488, 4608, &[128, 1, 3, 3]), Some(&self.weight_f32(7494096, 512, &[128])), &[1, 1], 128, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _model_23_one2one_cv4_1_one2one_cv4_1_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_cv2_act_Mul_output_0, &self.weight_f32(7494608, 147456, &[32, 128, 3, 3]), Some(&self.weight_f32(7642064, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let _model_23_proto_feat_refine_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_19_cv2_act_Mul_output_0, &self.weight_f32(7642192, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(7674960, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_20_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_20_conv_Conv_output_0, &mut ws.buf_8);
        let _model_23_one2one_cv2_1_one2one_cv2_1_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_1_one2one_cv2_1_0_conv_Conv_output_0, &mut ws.buf_9);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_one2one_cv4_1_one2one_cv4_1_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_1_one2one_cv4_1_0_conv_Conv_output_0, &mut ws.buf_14);
        let _model_23_proto_feat_refine_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_feat_refine_0_conv_Conv_output_0, &mut ws.buf_15);
        let _model_20_act_Mul_output_0 = lele::kernels::mul(&_model_20_conv_Conv_output_0, &_model_20_act_Sigmoid_output_0, &mut ws.buf_11);
        let _model_23_one2one_cv2_1_one2one_cv2_1_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_1_one2one_cv2_1_0_conv_Conv_output_0, &_model_23_one2one_cv2_1_one2one_cv2_1_0_act_Sigmoid_output_0, &mut ws.buf_16);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_conv_Conv_output_0, &_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_act_Sigmoid_output_0, &mut ws.buf_17);
        let _model_23_one2one_cv4_1_one2one_cv4_1_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_1_one2one_cv4_1_0_conv_Conv_output_0, &_model_23_one2one_cv4_1_one2one_cv4_1_0_act_Sigmoid_output_0, &mut ws.buf_18);
        let _model_23_proto_feat_refine_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_proto_feat_refine_0_conv_Conv_output_0, &_model_23_proto_feat_refine_0_act_Sigmoid_output_0, &mut ws.buf_19);
        let _model_21_Concat_output_0 = lele::kernels::concat(&[&_model_20_act_Mul_output_0, &_model_10_cv2_act_Mul_output_0], 1, &mut ws.buf_20);
        let _model_23_one2one_cv2_1_one2one_cv2_1_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_1_one2one_cv2_1_0_act_Mul_output_0, &self.weight_f32(7675216, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(7684432, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_0_act_Mul_output_0, &self.weight_f32(7684496, 40960, &[80, 128, 1, 1]), Some(&self.weight_f32(7725456, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_23_one2one_cv4_1_one2one_cv4_1_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_1_one2one_cv4_1_0_act_Mul_output_0, &self.weight_f32(7725776, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(7762640, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let _model_23_proto_Resize_output_0 = lele::kernels::resize_nearest(&_model_23_proto_feat_refine_0_act_Mul_output_0, None, Some(&self.weight_i64(7762768, 32, &[4]).data.iter().map(|&v| v as i64).collect::<Vec<_>>()), "asymmetric", &mut ws.buf_1);
        let _model_22_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_21_Concat_output_0, &self.weight_f32(7762800, 393216, &[256, 384, 1, 1]), Some(&self.weight_f32(8156016, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_23_one2one_cv2_1_one2one_cv2_1_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_1_one2one_cv2_1_1_conv_Conv_output_0, &mut ws.buf_0);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_conv_Conv_output_0, &mut ws.buf_9);
        let _model_23_one2one_cv4_1_one2one_cv4_1_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_1_one2one_cv4_1_1_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_proto_Add_output_0 = lele::kernels::add(&_model_16_cv2_act_Mul_output_0, &_model_23_proto_Resize_output_0, &mut ws.buf_11);
        let _model_22_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_22_cv1_conv_Conv_output_0, &mut ws.buf_12);
        let _model_23_one2one_cv2_1_one2one_cv2_1_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_1_one2one_cv2_1_1_conv_Conv_output_0, &_model_23_one2one_cv2_1_one2one_cv2_1_1_act_Sigmoid_output_0, &mut ws.buf_14);
        let _model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_conv_Conv_output_0, &_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_act_Sigmoid_output_0, &mut ws.buf_15);
        let _model_23_one2one_cv4_1_one2one_cv4_1_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_1_one2one_cv4_1_1_conv_Conv_output_0, &_model_23_one2one_cv4_1_one2one_cv4_1_1_act_Sigmoid_output_0, &mut ws.buf_16);
        let _model_22_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_22_cv1_conv_Conv_output_0, &_model_22_cv1_act_Sigmoid_output_0, &mut ws.buf_17);
        let _model_23_one2one_cv2_1_one2one_cv2_1_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_1_one2one_cv2_1_1_act_Mul_output_0, &self.weight_f32(8157040, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(8157296, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_1_one2one_cv3_1_0_one2one_cv3_1_0_1_act_Mul_output_0, &self.weight_f32(8157312, 2880, &[80, 1, 3, 3]), Some(&self.weight_f32(8160192, 320, &[80])), &[1, 1], 80, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let _model_23_one2one_cv4_1_one2one_cv4_1_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_1_one2one_cv4_1_1_act_Mul_output_0, &self.weight_f32(8160512, 4096, &[32, 32, 1, 1]), Some(&self.weight_f32(8164608, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let splits_slice = &[128, 128];
        let mut split_results = lele::kernels::split_owned(&_model_22_cv1_act_Mul_output_0, 1, splits_slice);
        let _model_22_Split_output_1 = split_results.swap_remove(1);
        let _model_22_Split_output_0 = split_results.swap_remove(0);
        let _model_23_Reshape_1_output_0 = lele::kernels::reshape(&_model_23_one2one_cv2_1_one2one_cv2_1_2_Conv_output_0, &[1, 4, -1]);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_conv_Conv_output_0, &mut ws.buf_4);
        let _model_23_Reshape_7_output_0 = lele::kernels::reshape(&_model_23_one2one_cv4_1_one2one_cv4_1_2_Conv_output_0, &[1, 32, -1]);
        let _model_22_m_0_m_0_0_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_Split_output_1, &self.weight_f32(8164736, 294912, &[64, 128, 3, 3]), Some(&self.weight_f32(8459648, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_6);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_conv_Conv_output_0, &_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_act_Sigmoid_output_0, &mut ws.buf_9);
        let _model_22_m_0_m_0_0_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_22_m_0_m_0_0_cv1_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_0_act_Mul_output_0, &self.weight_f32(8459904, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(8485504, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_12);
        let _model_22_m_0_m_0_0_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_22_m_0_m_0_0_cv1_conv_Conv_output_0, &_model_22_m_0_m_0_0_cv1_act_Sigmoid_output_0, &mut ws.buf_14);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_conv_Conv_output_0, &mut ws.buf_15);
        let _model_22_m_0_m_0_0_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_m_0_m_0_0_cv1_act_Mul_output_0, &self.weight_f32(8485824, 294912, &[128, 64, 3, 3]), Some(&self.weight_f32(8780736, 512, &[128])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_16);
        let _model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_conv_Conv_output_0, &_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_act_Sigmoid_output_0, &mut ws.buf_4);
        let _model_22_m_0_m_0_0_cv2_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_22_m_0_m_0_0_cv2_conv_Conv_output_0, &mut ws.buf_7);
        let _model_23_one2one_cv3_1_one2one_cv3_1_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_1_one2one_cv3_1_1_one2one_cv3_1_1_1_act_Mul_output_0, &self.weight_f32(8781248, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(8806848, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_9);
        let _model_22_m_0_m_0_0_cv2_act_Mul_output_0 = lele::kernels::mul(&_model_22_m_0_m_0_0_cv2_conv_Conv_output_0, &_model_22_m_0_m_0_0_cv2_act_Sigmoid_output_0, &mut ws.buf_6);
        let _model_23_Reshape_4_output_0 = lele::kernels::reshape(&_model_23_one2one_cv3_1_one2one_cv3_1_2_Conv_output_0, &[1, 80, -1]);
        let _model_22_m_0_m_0_0_Add_output_0 = lele::kernels::add(&_model_22_Split_output_1, &_model_22_m_0_m_0_0_cv2_act_Mul_output_0, &mut ws.buf_10);
        let _model_22_m_0_m_0_1_attn_qkv_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_m_0_m_0_0_Add_output_0, &self.weight_f32(8807168, 131072, &[256, 128, 1, 1]), Some(&self.weight_f32(8938240, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_12);
        let _model_22_m_0_m_0_1_attn_Reshape_output_0 = lele::kernels::reshape(&_model_22_m_0_m_0_1_attn_qkv_conv_Conv_output_0, &[1, 2, 128, 400]);
        let splits_slice = &[32, 32, 64];
        let mut split_results = lele::kernels::split_owned(&_model_22_m_0_m_0_1_attn_Reshape_output_0, 2, splits_slice);
        let _model_22_m_0_m_0_1_attn_Split_output_2 = split_results.swap_remove(2);
        let _model_22_m_0_m_0_1_attn_Split_output_1 = split_results.swap_remove(1);
        let _model_22_m_0_m_0_1_attn_Split_output_0 = split_results.swap_remove(0);
        let _model_22_m_0_m_0_1_attn_Transpose_output_0 = lele::kernels::transpose(&_model_22_m_0_m_0_1_attn_Split_output_0, &[0, 1, 3, 2], &mut ws.buf_7);
        let _model_22_m_0_m_0_1_attn_Reshape_2_output_0 = lele::kernels::reshape(&_model_22_m_0_m_0_1_attn_Split_output_2, &[1, 128, 20, 20]);
        let _model_22_m_0_m_0_1_attn_MatMul_output_0 = lele::kernels::matmul(&_model_22_m_0_m_0_1_attn_Transpose_output_0, &_model_22_m_0_m_0_1_attn_Split_output_1, &mut ws.buf_6);
        let _model_22_m_0_m_0_1_attn_pe_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_m_0_m_0_1_attn_Reshape_2_output_0, &self.weight_f32(8939264, 4608, &[128, 1, 3, 3]), Some(&self.weight_f32(8943872, 512, &[128])), &[1, 1], 128, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_16);
        let _model_22_m_0_m_0_1_attn_Mul_output_0 = lele::kernels::mul(&_model_22_m_0_m_0_1_attn_MatMul_output_0, &self.weight_f32(4852416, 4, &[]), &mut ws.buf_17);
        let _model_22_m_0_m_0_1_attn_Softmax_output_0 = lele::kernels::softmax(&_model_22_m_0_m_0_1_attn_Mul_output_0, -1, &mut ws.buf_12);
        let _model_22_m_0_m_0_1_attn_Transpose_1_output_0 = lele::kernels::transpose(&_model_22_m_0_m_0_1_attn_Softmax_output_0, &[0, 1, 3, 2], &mut ws.buf_4);
        let _model_22_m_0_m_0_1_attn_MatMul_1_output_0 = lele::kernels::matmul(&_model_22_m_0_m_0_1_attn_Split_output_2, &_model_22_m_0_m_0_1_attn_Transpose_1_output_0, &mut ws.buf_18);
        let _model_22_m_0_m_0_1_attn_Reshape_1_output_0 = lele::kernels::reshape(&_model_22_m_0_m_0_1_attn_MatMul_1_output_0, &[1, 128, 20, 20]);
        let _model_22_m_0_m_0_1_attn_Add_output_0 = lele::kernels::add(&_model_22_m_0_m_0_1_attn_Reshape_1_output_0, &_model_22_m_0_m_0_1_attn_pe_conv_Conv_output_0, &mut ws.buf_7);
        let _model_22_m_0_m_0_1_attn_proj_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_m_0_m_0_1_attn_Add_output_0, &self.weight_f32(8944384, 65536, &[128, 128, 1, 1]), Some(&self.weight_f32(9009920, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_22_m_0_m_0_1_Add_output_0 = lele::kernels::add(&_model_22_m_0_m_0_0_Add_output_0, &_model_22_m_0_m_0_1_attn_proj_conv_Conv_output_0, &mut ws.buf_14);
        let _model_22_m_0_m_0_1_ffn_ffn_0_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_22_m_0_m_0_1_Add_output_0, &self.weight_f32(9010432, 131072, &[256, 128, 1, 1]), Some(&self.weight_f32(9141504, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_15);
        let _model_22_m_0_m_0_1_ffn_ffn_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_m_0_m_0_1_ffn_ffn_0_act_Mul_output_0, &self.weight_f32(9142528, 131072, &[128, 256, 1, 1]), Some(&self.weight_f32(9273600, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_16);
        let _model_22_m_0_m_0_1_Add_1_output_0 = lele::kernels::add(&_model_22_m_0_m_0_1_Add_output_0, &_model_22_m_0_m_0_1_ffn_ffn_1_conv_Conv_output_0, &mut ws.buf_7);
        let _model_22_Concat_output_0 = lele::kernels::concat(&[&_model_22_Split_output_0, &_model_22_Split_output_1, &_model_22_m_0_m_0_1_Add_1_output_0], 1, &mut ws.buf_6);
        let _model_22_cv2_act_Mul_output_0 = lele::kernels::conv2d_silu(&_model_22_Concat_output_0, &self.weight_f32(9274112, 393216, &[256, 384, 1, 1]), Some(&self.weight_f32(9667328, 1024, &[256])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let _model_23_one2one_cv2_2_one2one_cv2_2_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_cv2_act_Mul_output_0, &self.weight_f32(9668352, 147456, &[16, 256, 3, 3]), Some(&self.weight_f32(9815808, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_12);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_cv2_act_Mul_output_0, &self.weight_f32(9815872, 9216, &[256, 1, 3, 3]), Some(&self.weight_f32(9825088, 1024, &[256])), &[1, 1], 256, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_14);
        let _model_23_one2one_cv4_2_one2one_cv4_2_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_cv2_act_Mul_output_0, &self.weight_f32(9826112, 294912, &[32, 256, 3, 3]), Some(&self.weight_f32(10121024, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let _model_23_proto_feat_refine_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_22_cv2_act_Mul_output_0, &self.weight_f32(10121152, 65536, &[64, 256, 1, 1]), Some(&self.weight_f32(10186688, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_23_one2one_cv2_2_one2one_cv2_2_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_2_one2one_cv2_2_0_conv_Conv_output_0, &mut ws.buf_7);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_conv_Conv_output_0, &mut ws.buf_8);
        let _model_23_one2one_cv4_2_one2one_cv4_2_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_2_one2one_cv4_2_0_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_proto_feat_refine_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_feat_refine_1_conv_Conv_output_0, &mut ws.buf_15);
        let _model_23_one2one_cv2_2_one2one_cv2_2_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_2_one2one_cv2_2_0_conv_Conv_output_0, &_model_23_one2one_cv2_2_one2one_cv2_2_0_act_Sigmoid_output_0, &mut ws.buf_16);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_conv_Conv_output_0, &_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_act_Sigmoid_output_0, &mut ws.buf_4);
        let _model_23_one2one_cv4_2_one2one_cv4_2_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_2_one2one_cv4_2_0_conv_Conv_output_0, &_model_23_one2one_cv4_2_one2one_cv4_2_0_act_Sigmoid_output_0, &mut ws.buf_17);
        let _model_23_proto_feat_refine_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_proto_feat_refine_1_conv_Conv_output_0, &_model_23_proto_feat_refine_1_act_Sigmoid_output_0, &mut ws.buf_18);
        let _model_23_one2one_cv2_2_one2one_cv2_2_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_2_one2one_cv2_2_0_act_Mul_output_0, &self.weight_f32(10186944, 9216, &[16, 16, 3, 3]), Some(&self.weight_f32(10196160, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_19);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_0_act_Mul_output_0, &self.weight_f32(10196224, 81920, &[80, 256, 1, 1]), Some(&self.weight_f32(10278144, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_20);
        let _model_23_one2one_cv4_2_one2one_cv4_2_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_2_one2one_cv4_2_0_act_Mul_output_0, &self.weight_f32(10278464, 36864, &[32, 32, 3, 3]), Some(&self.weight_f32(10315328, 128, &[32])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let _model_23_proto_Resize_1_output_0 = lele::kernels::resize_nearest(&_model_23_proto_feat_refine_1_act_Mul_output_0, None, Some(&self.weight_i64(7762768, 32, &[4]).data.iter().map(|&v| v as i64).collect::<Vec<_>>()), "asymmetric", &mut ws.buf_8);
        let _model_23_one2one_cv2_2_one2one_cv2_2_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv2_2_one2one_cv2_2_1_conv_Conv_output_0, &mut ws.buf_5);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_conv_Conv_output_0, &mut ws.buf_6);
        let _model_23_one2one_cv4_2_one2one_cv4_2_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv4_2_one2one_cv4_2_1_conv_Conv_output_0, &mut ws.buf_10);
        let _model_23_proto_Add_1_output_0 = lele::kernels::add(&_model_23_proto_Add_output_0, &_model_23_proto_Resize_1_output_0, &mut ws.buf_4);
        let _model_23_one2one_cv2_2_one2one_cv2_2_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv2_2_one2one_cv2_2_1_conv_Conv_output_0, &_model_23_one2one_cv2_2_one2one_cv2_2_1_act_Sigmoid_output_0, &mut ws.buf_12);
        let _model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_conv_Conv_output_0, &_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_act_Sigmoid_output_0, &mut ws.buf_14);
        let _model_23_one2one_cv4_2_one2one_cv4_2_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv4_2_one2one_cv4_2_1_conv_Conv_output_0, &_model_23_one2one_cv4_2_one2one_cv4_2_1_act_Sigmoid_output_0, &mut ws.buf_15);
        let _model_23_proto_feat_fuse_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_proto_Add_1_output_0, &self.weight_f32(10315456, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(10462912, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_16);
        let _model_23_one2one_cv2_2_one2one_cv2_2_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv2_2_one2one_cv2_2_1_act_Mul_output_0, &self.weight_f32(10463168, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(10463424, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_17);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_2_one2one_cv3_2_0_one2one_cv3_2_0_1_act_Mul_output_0, &self.weight_f32(10463440, 2880, &[80, 1, 3, 3]), Some(&self.weight_f32(10466320, 320, &[80])), &[1, 1], 80, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_8);
        let _model_23_one2one_cv4_2_one2one_cv4_2_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv4_2_one2one_cv4_2_1_act_Mul_output_0, &self.weight_f32(10466640, 4096, &[32, 32, 1, 1]), Some(&self.weight_f32(10470736, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let _model_23_proto_feat_fuse_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_feat_fuse_conv_Conv_output_0, &mut ws.buf_6);
        let _model_23_Reshape_2_output_0 = lele::kernels::reshape(&_model_23_one2one_cv2_2_one2one_cv2_2_2_Conv_output_0, &[1, 4, -1]);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_conv_Conv_output_0, &mut ws.buf_4);
        let _model_23_Reshape_8_output_0 = lele::kernels::reshape(&_model_23_one2one_cv4_2_one2one_cv4_2_2_Conv_output_0, &[1, 32, -1]);
        let _model_23_proto_feat_fuse_act_Mul_output_0 = lele::kernels::mul(&_model_23_proto_feat_fuse_conv_Conv_output_0, &_model_23_proto_feat_fuse_act_Sigmoid_output_0, &mut ws.buf_7);
        let _model_23_Concat_output_0 = lele::kernels::concat(&[&_model_23_Reshape_output_0, &_model_23_Reshape_1_output_0, &_model_23_Reshape_2_output_0], -1, &mut ws.buf_10);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_conv_Conv_output_0, &_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_act_Sigmoid_output_0, &mut ws.buf_11);
        let _model_23_Concat_2_output_0 = lele::kernels::concat(&[&_model_23_Reshape_6_output_0, &_model_23_Reshape_7_output_0, &_model_23_Reshape_8_output_0], 2, &mut ws.buf_12);
        let _model_23_proto_cv1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_proto_feat_fuse_act_Mul_output_0, &self.weight_f32(10470864, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(10618320, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_14);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_0_act_Mul_output_0, &self.weight_f32(10618576, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(10644176, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_15);
        let _model_23_proto_cv1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_cv1_conv_Conv_output_0, &mut ws.buf_6);
        let _model_23_Slice_output_0 = lele::kernels::slice(&_model_23_Concat_output_0, &[0], &[2], &[1], &[], &mut ws.buf_1);
        let _model_23_Slice_1_output_0 = lele::kernels::slice(&_model_23_Concat_output_0, &[2], &[4], &[1], &[], &mut ws.buf_4);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_conv_Conv_output_0, &mut ws.buf_0);
        let _model_23_proto_cv1_act_Mul_output_0 = lele::kernels::mul(&_model_23_proto_cv1_conv_Conv_output_0, &_model_23_proto_cv1_act_Sigmoid_output_0, &mut ws.buf_3);
        let _model_23_Sub_output_0 = lele::kernels::sub(&self.weight_f32(10644560, 67200, &[1, 2, 8400]), &_model_23_Slice_output_0, &mut ws.buf_5);
        let _model_23_Add_1_output_0 = lele::kernels::add(&self.weight_f32(10644560, 67200, &[1, 2, 8400]), &_model_23_Slice_1_output_0, &mut ws.buf_7);
        let _model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_act_Mul_output_0 = lele::kernels::mul(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_conv_Conv_output_0, &_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_act_Sigmoid_output_0, &mut ws.buf_8);
        let _model_23_proto_upsample_ConvTranspose_output_0 = lele::kernels::conv_transpose(&_model_23_proto_cv1_act_Mul_output_0, &self.weight_f32(10711760, 65536, &[64, 64, 2, 2]), Some(&self.weight_f32(10777296, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[2, 2], &mut ws.buf_10);
        let _model_23_Concat_3_output_0 = lele::kernels::concat(&[&_model_23_Sub_output_0, &_model_23_Add_1_output_0], 1, &mut ws.buf_11);
        let _model_23_one2one_cv3_2_one2one_cv3_2_2_Conv_output_0 = lele::kernels::conv2d(&_model_23_one2one_cv3_2_one2one_cv3_2_1_one2one_cv3_2_1_1_act_Mul_output_0, &self.weight_f32(10777552, 25600, &[80, 80, 1, 1]), Some(&self.weight_f32(10803152, 320, &[80])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let _model_23_proto_cv2_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_proto_upsample_ConvTranspose_output_0, &self.weight_f32(10803472, 147456, &[64, 64, 3, 3]), Some(&self.weight_f32(10950928, 256, &[64])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let _model_23_Mul_2_output_0 = lele::kernels::mul(&_model_23_Concat_3_output_0, &self.weight_f32(10951184, 33600, &[1, 8400]), &mut ws.buf_4);
        let _model_23_Reshape_5_output_0 = lele::kernels::reshape(&_model_23_one2one_cv3_2_one2one_cv3_2_2_Conv_output_0, &[1, 80, -1]);
        let _model_23_proto_cv2_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_cv2_conv_Conv_output_0, &mut ws.buf_0);
        let _model_23_Concat_1_output_0 = lele::kernels::concat(&[&_model_23_Reshape_3_output_0, &_model_23_Reshape_4_output_0, &_model_23_Reshape_5_output_0], -1, &mut ws.buf_3);
        let _model_23_proto_cv2_act_Mul_output_0 = lele::kernels::mul(&_model_23_proto_cv2_conv_Conv_output_0, &_model_23_proto_cv2_act_Sigmoid_output_0, &mut ws.buf_5);
        let _model_23_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_Concat_1_output_0, &mut ws.buf_7);
        let _model_23_proto_cv3_conv_Conv_output_0 = lele::kernels::conv2d(&_model_23_proto_cv2_act_Mul_output_0, &self.weight_f32(10984784, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(10992976, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let _model_23_Concat_4_output_0 = lele::kernels::concat(&[&_model_23_Mul_2_output_0, &_model_23_Sigmoid_output_0, &_model_23_Concat_2_output_0], 1, &mut ws.buf_10);
        let _model_23_proto_cv3_act_Sigmoid_output_0 = lele::kernels::sigmoid(&_model_23_proto_cv3_conv_Conv_output_0, &mut ws.buf_11);
        let _model_23_Transpose_output_0 = lele::kernels::transpose(&_model_23_Concat_4_output_0, &[0, 2, 1], &mut ws.buf_2);
        let output1 = lele::kernels::mul(&_model_23_proto_cv3_conv_Conv_output_0, &_model_23_proto_cv3_act_Sigmoid_output_0, &mut ws.buf_0);
        let splits_slice = &[4, 80, 32];
        let mut split_results = lele::kernels::split_owned(&_model_23_Transpose_output_0, -1, splits_slice);
        let _model_23_Split_output_2 = split_results.swap_remove(2);
        let _model_23_Split_output_1 = split_results.swap_remove(1);
        let _model_23_Split_output_0 = split_results.swap_remove(0);
        let _model_23_ReduceMax_output_0 = lele::kernels::reduce_max(&_model_23_Split_output_1, &[-1], false, &mut ws.buf_5);
        let mut buf__model_23_TopK_output_0_values = Vec::<f32>::new();
        let mut buf__model_23_TopK_output_0_indices = Vec::<f32>::new();
        let (_model_23_TopK_output_0, _model_23_TopK_output_1) = lele::kernels::topk(&_model_23_ReduceMax_output_0, self.weight_i64(10993152, 8, &[1]).data[0] as usize, -1, true, true, &mut buf__model_23_TopK_output_0_values, &mut buf__model_23_TopK_output_0_indices);
        let _model_23_Expand_output_0 = lele::kernels::unsqueeze(&_model_23_TopK_output_1, &[-1]);
        let _model_23_Flatten_1_output_0 = lele::kernels::flatten(&_model_23_Expand_output_0, 2);
        let _model_23_Tile_output_0 = lele::kernels::tile(&_model_23_Expand_output_0, &[1, 1, 80], &mut ws.buf_8);
        let _model_23_GatherElements_output_0 = lele::kernels::gather_elements(&_model_23_Split_output_1, &_model_23_Tile_output_0, 1, &mut ws.buf_2);
        let _model_23_Flatten_output_0 = lele::kernels::flatten(&_model_23_GatherElements_output_0, 1);
        let mut buf__model_23_TopK_1_output_0_values = Vec::<f32>::new();
        let mut buf__model_23_TopK_1_output_0_indices = Vec::<f32>::new();
        let (_model_23_TopK_1_output_0, _model_23_TopK_1_output_1) = lele::kernels::topk(&_model_23_Flatten_output_0, self.weight_i64(10993152, 8, &[1]).data[0] as usize, -1, true, true, &mut buf__model_23_TopK_1_output_0_values, &mut buf__model_23_TopK_1_output_0_indices);
        let _model_23_Add_2_output_0 = lele::kernels::div(&_model_23_TopK_1_output_1, &self.weight_i64_f32(10993200, 8, &[]), &mut ws.buf_11);
        let _model_23_Unsqueeze_1_output_0 = lele::kernels::unsqueeze(&_model_23_TopK_1_output_0, &[2]);
        let _model_23_Mod_output_0 = lele::kernels::mod_f32(&_model_23_TopK_1_output_1, &self.weight_i64_f32(10993200, 8, &[]), &mut ws.buf_12);
        let _model_23_Unsqueeze_2_output_0 = lele::kernels::unsqueeze(&_model_23_Mod_output_0, &[2]);
        let _model_23_Expand_2_output_0 = lele::kernels::gather(&_model_23_Flatten_1_output_0, &_model_23_Add_2_output_0, 0, &mut ws.buf_3);
        let _model_23_Cast_2_output_0 = _model_23_Unsqueeze_2_output_0.clone(); // Cast f32->f32 is no-op
        let _model_23_Tile_1_output_0 = lele::kernels::tile(&_model_23_Expand_2_output_0, &[1, 1, 4], &mut ws.buf_7);
        let _model_23_Tile_2_output_0 = lele::kernels::tile(&_model_23_Expand_2_output_0, &[1, 1, 32], &mut ws.buf_8);
        let _model_23_GatherElements_1_output_0 = lele::kernels::gather_elements(&_model_23_Split_output_0, &_model_23_Tile_1_output_0, 1, &mut ws.buf_10);
        let _model_23_GatherElements_2_output_0 = lele::kernels::gather_elements(&_model_23_Split_output_2, &_model_23_Tile_2_output_0, 1, &mut ws.buf_13);
        let output0 = lele::kernels::concat(&[&_model_23_GatherElements_1_output_0, &_model_23_Unsqueeze_1_output_0, &_model_23_Cast_2_output_0, &_model_23_GatherElements_2_output_0], -1, &mut ws.buf_9);
        (output0.to_owned(), output1.to_owned())
    }


    #[cfg(target_arch = "aarch64")]
    fn get_prepared_weight(&self, offset: usize, len: usize, k: usize, n: usize) -> std::sync::Arc<lele::kernels::PreparedWeightsArm> {
        let key = (offset, len);
        {
            let cache = self.prepared_weights_cache.borrow();
            if let Some(pw) = cache.get(&key) {
                return pw.clone();
            }
        }
        let raw_bytes = &self.data[offset..offset+len];
        let pw = std::sync::Arc::new(lele::kernels::prepare_weights_arm(raw_bytes, k, n));
        self.prepared_weights_cache.borrow_mut().insert(key, pw.clone());
        pw
    }
    fn weight_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'a, f32> {
        TensorView::from_bytes_f32(&self.data[offset..offset+len], shape)
    }
    fn weight_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i32_as_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i32> {
        TensorView::from_bytes_i32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i64_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i64_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i32_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_u8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_f16(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_f16(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8_raw(&self, offset: usize, len: usize) -> &'a [u8] {
        &self.data[offset..offset+len]
    }

    // Inference Entry Point
    pub fn forward(&self, images: TensorView<'a>) -> (TensorView<'static>, TensorView<'static>) {
        let mut ws = Yolo26SegWorkspace::new();
        let res = self.forward_with_workspace(&mut ws, images);
        (res.0.to_owned(), res.1.to_owned())
    }
    pub fn forward_with_workspace<'w>(&self, ws: &'w mut Yolo26SegWorkspace, images: TensorView<'w>) -> (TensorView<'w>, TensorView<'w>) {
        let (output0, output1) = self.run_chunk_0(ws, images);
        (output0, output1)
    }
}
