// Auto-generated by lele_compiler
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
use lele::tensor::TensorView;
use lele::kernels::*;


#[derive(Default)]
pub struct PpocrRecWorkspace {
    pub buf_0: Vec<f32>,
    pub buf_1: Vec<f32>,
    pub buf_2: Vec<f32>,
    pub buf_3: Vec<f32>,
    pub buf_4: Vec<f32>,
    pub buf_5: Vec<f32>,
    pub buf_6: Vec<f32>,
    pub buf_7: Vec<f32>,
    pub buf_8: Vec<f32>,
}
impl PpocrRecWorkspace {
    pub fn new() -> Self {
        Self::default()
    }
}

pub struct PpocrRec<'a> {
    data: &'a [u8],
    _phantom: std::marker::PhantomData<&'a ()>,
    #[cfg(target_arch = "aarch64")]
    prepared_weights_cache: std::cell::RefCell<std::collections::HashMap<(usize, usize), std::sync::Arc<lele::kernels::PreparedWeightsArm>>>,
}

impl<'a> PpocrRec<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            _phantom: std::marker::PhantomData,
            #[cfg(target_arch = "aarch64")]
            prepared_weights_cache: std::cell::RefCell::new(std::collections::HashMap::new()),
        }
    }
fn conv1d_relu<'c, 'd>(
    &self,
    input: lele::tensor::TensorView<'c>,
    weight: lele::tensor::TensorView<'c>,
    bias: Option<&lele::tensor::TensorView<'c>>,
    stride: usize,
    dilation: usize,
    groups: usize,
    padding: usize,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::conv1d_fused(
        &input,
        &weight,
        bias,
        &[dilation as i64],
        groups as i64,
        &[padding as i64, padding as i64],
        &[stride as i64],
        true,
        output_buf,
    )
}
fn layer_norm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    scale: lele::tensor::TensorView<'c>,
    bias: lele::tensor::TensorView<'c>,
    epsilon: lele::tensor::TensorView<'c>,
    _two: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    let eps = epsilon.data.first().cloned().unwrap_or(1e-5);
    lele::kernels::layer_norm(input, &scale, &bias, -1, eps, output_buf)
}
fn linear_quantized<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, false, output_buf,
    )
}

fn linear_quantized_relu<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, true, output_buf,
    )
}

#[cfg(target_arch = "aarch64")]
fn linear_quantized_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        false,
        output_buf,
    )
}

/// ARM-optimized quantized linear + ReLU with pre-packed weights.
/// Uses fused DynQuant+GEMM: eliminates f32 intermediate buffer, per-call u8
/// allocation, and separate f32→u8 conversion pass.
#[cfg(target_arch = "aarch64")]
fn linear_quantized_relu_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        true,
        output_buf,
    )
}

/// ARM-optimized MatMulInteger with pre-packed weight cache.
/// Used for unfused MatMulInteger nodes where B is a static model weight.
/// Eliminates: per-call B packing, B u8→f32→u8 roundtrip, heap alloc.
#[cfg(target_arch = "aarch64")]
fn mat_mul_integer_arm<'c, 'd>(
    &self,
    a: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    a_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    b_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_a = a_zero_point.and_then(|z| z.data.first().cloned());
    let zp_b = b_zero_point.and_then(|z| z.data.first()).map(|&v| v as u8);

    lele::kernels::mat_mul_integer_prepared_arm(a, &pw, zp_a, zp_b, None, None, false, output_buf)
}

// Helper for pre-quantized inputs (used in attention where input is already quantized)
#[inline]
fn linear_quantized_prequant<'c, 'd>(
    &self,
    input_quantized: &lele::tensor::TensorView<'c, f32>,
    input_scale: &lele::tensor::TensorView<'c, f32>,
    input_zero_point: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
    scale_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let combined_scale = lele::kernels::mul(input_scale, &weight_scale, scale_buf);

    // FUSED: MatMul + Scale + Bias in one operation
    lele::kernels::mat_mul_integer_with_scale_bias(
        input_quantized,
        &weight_int8,
        Some(input_zero_point),
        Some(&weight_zero),
        Some(&combined_scale),
        Some(&bias),
        output_buf,
    )
}
fn linear<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    weight: &lele::tensor::TensorView<'c>,
    bias: &lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::matmul_fused_add(input, weight, bias, output_buf)
}

fn embedding_concat<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: f32,
    weight: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    // ConstantOfShape + Concat pattern
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

fn embedding_concat_i64<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: i64,
    weight: lele::tensor::TensorView<'c, i64>,
    output_buf: &'d mut Vec<i64>,
) -> lele::tensor::TensorView<'d, i64> {
    // ConstantOfShape + Concat pattern (i64)
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

    #[inline(never)]
    fn run_chunk_0<'w>(&self, ws: &'w mut PpocrRecWorkspace, x: TensorView<'w, f32>) -> TensorView<'static, f32> {
        let p2o_pd_op_conv2d_0_0 = lele::kernels::conv2d(&x, &self.weight_f32(0, 2592, &[24, 3, 3, 3]), None, &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_0);
        let p2o_pd_op_batch_norm__0_0 = lele::kernels::batch_norm(&p2o_pd_op_conv2d_0_0, &self.weight_f32(2592, 96, &[24]), &self.weight_f32(2688, 96, &[24]), &self.weight_f32(2784, 96, &[24]), &self.weight_f32(2880, 96, &[24]), 1e-5, &mut ws.buf_1);
        let auto_cast_0 = p2o_pd_op_batch_norm__0_0.clone();
        let p2o_pd_op_gelu_0_0 = lele::kernels::gelu(&auto_cast_0, &mut ws.buf_0);
        let p2o_pd_op_conv2d_1_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_0_0, &self.weight_f32(3024, 41472, &[48, 24, 3, 3]), None, &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_6);
        let p2o_pd_op_batch_norm__1_0 = lele::kernels::batch_norm(&p2o_pd_op_conv2d_1_0, &self.weight_f32(44496, 192, &[48]), &self.weight_f32(44688, 192, &[48]), &self.weight_f32(44880, 192, &[48]), &self.weight_f32(45072, 192, &[48]), 1e-5, &mut ws.buf_7);
        let Add_3 = lele::kernels::conv2d(&p2o_pd_op_batch_norm__1_0, &self.weight_f32(45264, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(46992, 192, &[1, 48, 1, 1])), &[1, 1], 48, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_add_0_0 = Add_3.clone();
        let ReduceMean_1 = lele::kernels::reduce_mean(&p2o_pd_op_add_0_0, &[2, 3], true, &mut ws.buf_1);
        let p2o_pd_op_mean_0_0 = ReduceMean_1.clone();
        let Add_5 = lele::kernels::conv2d(&p2o_pd_op_mean_0_0, &self.weight_f32(47184, 2304, &[12, 48, 1, 1]), Some(&self.weight_f32(49488, 48, &[1, 12, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_1_0 = Add_5.clone();
        let p2o_pd_op_relu_0_0 = lele::kernels::relu(&p2o_pd_op_add_1_0, &mut ws.buf_2);
        let Add_7 = lele::kernels::conv2d(&p2o_pd_op_relu_0_0, &self.weight_f32(49536, 2304, &[48, 12, 1, 1]), Some(&self.weight_f32(51840, 192, &[1, 48, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_add_2_0 = Add_7.clone();
        let p2o_pd_op_hardsigmoid_0_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_add_2_0, 0.1666667, 0.5, &mut ws.buf_0);
        let Mul_4 = lele::kernels::mul(&p2o_pd_op_add_0_0, &p2o_pd_op_hardsigmoid_0_0, &mut ws.buf_1);
        let p2o_pd_op_multiply_0_0 = Mul_4.clone();
        let Add_9 = lele::kernels::conv2d(&p2o_pd_op_multiply_0_0, &self.weight_f32(52032, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(70464, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_3_0 = Add_9.clone();
        let auto_cast_5 = p2o_pd_op_add_3_0.clone();
        let p2o_pd_op_gelu_1_0 = lele::kernels::gelu(&auto_cast_5, &mut ws.buf_7);
        let Add_13 = lele::kernels::conv2d(&p2o_pd_op_gelu_1_0, &self.weight_f32(70848, 18432, &[48, 96, 1, 1]), Some(&self.weight_f32(89280, 192, &[1, 48, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_4_0 = Add_13.clone();
        let Add_15 = lele::kernels::add(&p2o_pd_op_multiply_0_0, &p2o_pd_op_add_4_0, &mut ws.buf_0);
        let p2o_pd_op_add_5_0 = Add_15.clone();
        let Add_17 = lele::kernels::conv2d(&p2o_pd_op_add_5_0, &self.weight_f32(89472, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(91200, 192, &[1, 48, 1, 1])), &[1, 1], 48, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_add_6_0 = Add_17.clone();
        let Add_19 = lele::kernels::conv2d(&p2o_pd_op_add_6_0, &self.weight_f32(91392, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(109824, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let p2o_pd_op_add_7_0 = Add_19.clone();
        let auto_cast_9 = p2o_pd_op_add_7_0.clone();
        let p2o_pd_op_gelu_2_0 = lele::kernels::gelu(&auto_cast_9, &mut ws.buf_7);
        let Add_23 = lele::kernels::conv2d(&p2o_pd_op_gelu_2_0, &self.weight_f32(110208, 18432, &[48, 96, 1, 1]), Some(&self.weight_f32(128640, 192, &[1, 48, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_8_0 = Add_23.clone();
        let Add_25 = lele::kernels::add(&p2o_pd_op_add_6_0, &p2o_pd_op_add_8_0, &mut ws.buf_2);
        let p2o_pd_op_add_9_0 = Add_25.clone();
        let Add_27 = lele::kernels::conv2d(&p2o_pd_op_add_9_0, &self.weight_f32(128832, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(130560, 192, &[1, 48, 1, 1])), &[1, 1], 48, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_4);
        let p2o_pd_op_add_10_0 = Add_27.clone();
        let Add_29 = lele::kernels::conv2d(&p2o_pd_op_add_10_0, &self.weight_f32(130752, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(149184, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_add_11_0 = Add_29.clone();
        let auto_cast_13 = p2o_pd_op_add_11_0.clone();
        let p2o_pd_op_gelu_3_0 = lele::kernels::gelu(&auto_cast_13, &mut ws.buf_6);
        let Add_33 = lele::kernels::conv2d(&p2o_pd_op_gelu_3_0, &self.weight_f32(149568, 36864, &[96, 96, 1, 1]), Some(&self.weight_f32(186432, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let p2o_pd_op_add_12_0 = Add_33.clone();
        let Add_35 = lele::kernels::conv2d(&p2o_pd_op_add_12_0, &self.weight_f32(186816, 3456, &[96, 1, 3, 3]), Some(&self.weight_f32(190272, 384, &[1, 96, 1, 1])), &[1, 1], 96, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_add_13_0 = Add_35.clone();
        let ReduceMean_3 = lele::kernels::reduce_mean(&p2o_pd_op_add_13_0, &[2, 3], true, &mut ws.buf_1);
        let p2o_pd_op_mean_1_0 = ReduceMean_3.clone();
        let Add_37 = lele::kernels::conv2d(&p2o_pd_op_mean_1_0, &self.weight_f32(190656, 9216, &[24, 96, 1, 1]), Some(&self.weight_f32(199872, 96, &[1, 24, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_14_0 = Add_37.clone();
        let p2o_pd_op_relu_1_0 = lele::kernels::relu(&p2o_pd_op_add_14_0, &mut ws.buf_0);
        let Add_39 = lele::kernels::conv2d(&p2o_pd_op_relu_1_0, &self.weight_f32(199968, 9216, &[96, 24, 1, 1]), Some(&self.weight_f32(209184, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_add_15_0 = Add_39.clone();
        let p2o_pd_op_hardsigmoid_1_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_add_15_0, 0.1666667, 0.5, &mut ws.buf_1);
        let Mul_15 = lele::kernels::mul(&p2o_pd_op_add_13_0, &p2o_pd_op_hardsigmoid_1_0, &mut ws.buf_3);
        let p2o_pd_op_multiply_1_0 = Mul_15.clone();
        let Add_41 = lele::kernels::conv2d(&p2o_pd_op_multiply_1_0, &self.weight_f32(209568, 73728, &[192, 96, 1, 1]), Some(&self.weight_f32(283296, 768, &[1, 192, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_16_0 = Add_41.clone();
        let auto_cast_19 = p2o_pd_op_add_16_0.clone();
        let p2o_pd_op_gelu_4_0 = lele::kernels::gelu(&auto_cast_19, &mut ws.buf_7);
        let Add_45 = lele::kernels::conv2d(&p2o_pd_op_gelu_4_0, &self.weight_f32(284064, 73728, &[96, 192, 1, 1]), Some(&self.weight_f32(357792, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_17_0 = Add_45.clone();
        let Add_47 = lele::kernels::add(&p2o_pd_op_multiply_1_0, &p2o_pd_op_add_17_0, &mut ws.buf_1);
        let p2o_pd_op_add_18_0 = Add_47.clone();
        let Add_49 = lele::kernels::conv2d(&p2o_pd_op_add_18_0, &self.weight_f32(358176, 3456, &[96, 1, 3, 3]), Some(&self.weight_f32(361632, 384, &[1, 96, 1, 1])), &[1, 1], 96, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_add_19_0 = Add_49.clone();
        let Add_51 = lele::kernels::conv2d(&p2o_pd_op_add_19_0, &self.weight_f32(362016, 73728, &[192, 96, 1, 1]), Some(&self.weight_f32(435744, 768, &[1, 192, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_add_20_0 = Add_51.clone();
        let auto_cast_23 = p2o_pd_op_add_20_0.clone();
        let p2o_pd_op_gelu_5_0 = lele::kernels::gelu(&auto_cast_23, &mut ws.buf_7);
        let Add_55 = lele::kernels::conv2d(&p2o_pd_op_gelu_5_0, &self.weight_f32(436512, 73728, &[96, 192, 1, 1]), Some(&self.weight_f32(510240, 384, &[1, 96, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_21_0 = Add_55.clone();
        let Add_57 = lele::kernels::add(&p2o_pd_op_add_19_0, &p2o_pd_op_add_21_0, &mut ws.buf_0);
        let p2o_pd_op_add_22_0 = Add_57.clone();
        let Add_59 = lele::kernels::conv2d(&p2o_pd_op_add_22_0, &self.weight_f32(510624, 3456, &[96, 1, 3, 3]), Some(&self.weight_f32(514080, 384, &[1, 96, 1, 1])), &[1, 1], 96, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_4);
        let p2o_pd_op_add_23_0 = Add_59.clone();
        let Add_61 = lele::kernels::conv2d(&p2o_pd_op_add_23_0, &self.weight_f32(514464, 73728, &[192, 96, 1, 1]), Some(&self.weight_f32(588192, 768, &[1, 192, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_add_24_0 = Add_61.clone();
        let auto_cast_27 = p2o_pd_op_add_24_0.clone();
        let p2o_pd_op_gelu_6_0 = lele::kernels::gelu(&auto_cast_27, &mut ws.buf_6);
        let Add_65 = lele::kernels::conv2d(&p2o_pd_op_gelu_6_0, &self.weight_f32(588960, 122880, &[160, 192, 1, 1]), Some(&self.weight_f32(711840, 640, &[1, 160, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let p2o_pd_op_add_25_0 = Add_65.clone();
        let Add_67 = lele::kernels::conv2d(&p2o_pd_op_add_25_0, &self.weight_f32(712480, 5760, &[160, 1, 3, 3]), Some(&self.weight_f32(718240, 640, &[1, 160, 1, 1])), &[1, 1], 160, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_add_26_0 = Add_67.clone();
        let ReduceMean_5 = lele::kernels::reduce_mean(&p2o_pd_op_add_26_0, &[2, 3], true, &mut ws.buf_3);
        let p2o_pd_op_mean_2_0 = ReduceMean_5.clone();
        let Add_69 = lele::kernels::conv2d(&p2o_pd_op_mean_2_0, &self.weight_f32(718880, 25600, &[40, 160, 1, 1]), Some(&self.weight_f32(744480, 160, &[1, 40, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_27_0 = Add_69.clone();
        let p2o_pd_op_relu_2_0 = lele::kernels::relu(&p2o_pd_op_add_27_0, &mut ws.buf_1);
        let Add_71 = lele::kernels::conv2d(&p2o_pd_op_relu_2_0, &self.weight_f32(744640, 25600, &[160, 40, 1, 1]), Some(&self.weight_f32(770240, 640, &[1, 160, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_add_28_0 = Add_71.clone();
        let p2o_pd_op_hardsigmoid_2_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_add_28_0, 0.1666667, 0.5, &mut ws.buf_2);
        let Mul_26 = lele::kernels::mul(&p2o_pd_op_add_26_0, &p2o_pd_op_hardsigmoid_2_0, &mut ws.buf_3);
        let p2o_pd_op_multiply_2_0 = Mul_26.clone();
        let Add_73 = lele::kernels::conv2d(&p2o_pd_op_multiply_2_0, &self.weight_f32(770880, 204800, &[320, 160, 1, 1]), Some(&self.weight_f32(975680, 1280, &[1, 320, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_29_0 = Add_73.clone();
        let auto_cast_33 = p2o_pd_op_add_29_0.clone();
        let p2o_pd_op_gelu_7_0 = lele::kernels::gelu(&auto_cast_33, &mut ws.buf_7);
        let Add_77 = lele::kernels::conv2d(&p2o_pd_op_gelu_7_0, &self.weight_f32(976960, 204800, &[160, 320, 1, 1]), Some(&self.weight_f32(1181760, 640, &[1, 160, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_30_0 = Add_77.clone();
        let Add_79 = lele::kernels::add(&p2o_pd_op_multiply_2_0, &p2o_pd_op_add_30_0, &mut ws.buf_0);
        let p2o_pd_op_add_31_0 = Add_79.clone();
        let Add_81 = lele::kernels::conv2d(&p2o_pd_op_add_31_0, &self.weight_f32(1182400, 5760, &[160, 1, 3, 3]), Some(&self.weight_f32(1188160, 640, &[1, 160, 1, 1])), &[1, 1], 160, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_add_32_0 = Add_81.clone();
        let Add_83 = lele::kernels::conv2d(&p2o_pd_op_add_32_0, &self.weight_f32(1188800, 204800, &[320, 160, 1, 1]), Some(&self.weight_f32(1393600, 1280, &[1, 320, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_add_33_0 = Add_83.clone();
        let auto_cast_37 = p2o_pd_op_add_33_0.clone();
        let p2o_pd_op_gelu_8_0 = lele::kernels::gelu(&auto_cast_37, &mut ws.buf_7);
        let Add_87 = lele::kernels::conv2d(&p2o_pd_op_gelu_8_0, &self.weight_f32(1394880, 204800, &[160, 320, 1, 1]), Some(&self.weight_f32(1599680, 640, &[1, 160, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_34_0 = Add_87.clone();
        let Add_89 = lele::kernels::add(&p2o_pd_op_add_32_0, &p2o_pd_op_add_34_0, &mut ws.buf_1);
        let p2o_pd_op_add_35_0 = Add_89.clone();
        let Add_91 = lele::kernels::conv2d(&p2o_pd_op_add_35_0, &self.weight_f32(1600320, 5760, &[160, 1, 3, 3]), Some(&self.weight_f32(1606080, 640, &[1, 160, 1, 1])), &[1, 1], 160, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_add_36_0 = Add_91.clone();
        let Add_93 = lele::kernels::conv2d(&p2o_pd_op_add_36_0, &self.weight_f32(1606720, 204800, &[320, 160, 1, 1]), Some(&self.weight_f32(1811520, 1280, &[1, 320, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_add_37_0 = Add_93.clone();
        let auto_cast_41 = p2o_pd_op_add_37_0.clone();
        let p2o_pd_op_gelu_9_0 = lele::kernels::gelu(&auto_cast_41, &mut ws.buf_7);
        let Add_97 = lele::kernels::conv2d(&p2o_pd_op_gelu_9_0, &self.weight_f32(1812800, 204800, &[160, 320, 1, 1]), Some(&self.weight_f32(2017600, 640, &[1, 160, 1, 1])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_8);
        let p2o_pd_op_add_38_0 = Add_97.clone();
        let Add_99 = lele::kernels::add(&p2o_pd_op_add_36_0, &p2o_pd_op_add_38_0, &mut ws.buf_0);
        let p2o_pd_op_add_39_0 = Add_99.clone();
        let p2o_pd_op_pool2d_0_0 = lele::kernels::average_pool2d(&p2o_pd_op_add_39_0, &[3, 2], &[3, 2], &[0, 0, 0, 0], false, &mut ws.buf_1);
        let p2o_pd_op_squeeze_0_0 = lele::kernels::squeeze(&p2o_pd_op_pool2d_0_0, Some(&[2]));
        let p2o_pd_op_transpose_0_0 = lele::kernels::transpose(&p2o_pd_op_squeeze_0_0, &[0, 2, 1], &mut ws.buf_2);
        let p2o_pd_op_transpose_1_0 = lele::kernels::transpose(&p2o_pd_op_transpose_0_0, &[0, 2, 1], &mut ws.buf_3);
        let p2o_pd_op_unsqueeze_1_0 = lele::kernels::unsqueeze(&p2o_pd_op_transpose_1_0, &[2]);
        let p2o_pd_op_depthwise_conv2d_9_0 = lele::kernels::conv2d(&p2o_pd_op_unsqueeze_1_0, &self.weight_f32(2018240, 3200, &[160, 1, 1, 5]), None, &[1, 1], 160, &[0, 2, 0, 2], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_squeeze_1_0 = lele::kernels::squeeze(&p2o_pd_op_depthwise_conv2d_9_0, Some(&[2]));
        let p2o_pd_op_batch_norm__2_0 = lele::kernels::batch_norm(&p2o_pd_op_squeeze_1_0, &self.weight_f32(2021440, 640, &[160]), &self.weight_f32(2022080, 640, &[160]), &self.weight_f32(2022720, 640, &[160]), &self.weight_f32(2023360, 640, &[160]), 1e-5, &mut ws.buf_0);
        let HardSigmoid_4 = lele::kernels::hard_sigmoid(&p2o_pd_op_batch_norm__2_0, 0.16666667, 0.5, &mut ws.buf_1);
        let p2o_pd_op_hardswish_0_0 = lele::kernels::mul(&HardSigmoid_4, &p2o_pd_op_batch_norm__2_0, &mut ws.buf_2);
        let p2o_pd_op_unsqueeze_3_0 = lele::kernels::unsqueeze(&p2o_pd_op_hardswish_0_0, &[2]);
        let p2o_pd_op_conv2d_26_0 = lele::kernels::conv2d(&p2o_pd_op_unsqueeze_3_0, &self.weight_f32(2024000, 102400, &[160, 160, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_squeeze_2_0 = lele::kernels::squeeze(&p2o_pd_op_conv2d_26_0, Some(&[2]));
        let p2o_pd_op_batch_norm__3_0 = lele::kernels::batch_norm(&p2o_pd_op_squeeze_2_0, &self.weight_f32(2126400, 640, &[160]), &self.weight_f32(2127040, 640, &[160]), &self.weight_f32(2127680, 640, &[160]), &self.weight_f32(2128320, 640, &[160]), 1e-5, &mut ws.buf_4);
        let HardSigmoid_6 = lele::kernels::hard_sigmoid(&p2o_pd_op_batch_norm__3_0, 0.16666667, 0.5, &mut ws.buf_5);
        let p2o_pd_op_hardswish_1_0 = lele::kernels::mul(&HardSigmoid_6, &p2o_pd_op_batch_norm__3_0, &mut ws.buf_0);
        let p2o_pd_op_transpose_2_0 = lele::kernels::transpose(&p2o_pd_op_hardswish_1_0, &[0, 2, 1], &mut ws.buf_1);
        let Add_105 = self.linear(&p2o_pd_op_transpose_2_0, &self.weight_f32(2128960, 51200, &[160, 80]), &self.weight_f32(2180160, 320, &[80]), &mut ws.buf_6);
        let p2o_pd_op_add_40_0 = Add_105.clone();
        let Add_107 = self.linear(&p2o_pd_op_add_40_0, &self.weight_f32(2180480, 2209920, &[80, 6906]), &self.weight_f32(4390400, 27624, &[6906]), &mut ws.buf_4);
        let p2o_pd_op_add_41_0 = Add_107.clone();
        let fetch_name_0 = lele::kernels::softmax(&p2o_pd_op_add_41_0, 2, &mut ws.buf_0);
        unsafe { fetch_name_0.detach_or_own() }
    }


    #[cfg(target_arch = "aarch64")]
    fn get_prepared_weight(&self, offset: usize, len: usize, k: usize, n: usize) -> std::sync::Arc<lele::kernels::PreparedWeightsArm> {
        let key = (offset, len);
        {
            let cache = self.prepared_weights_cache.borrow();
            if let Some(pw) = cache.get(&key) {
                return pw.clone();
            }
        }
        let raw_bytes = &self.data[offset..offset+len];
        let pw = std::sync::Arc::new(lele::kernels::prepare_weights_arm(raw_bytes, k, n));
        self.prepared_weights_cache.borrow_mut().insert(key, pw.clone());
        pw
    }
    fn weight_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'a, f32> {
        TensorView::from_bytes_f32(&self.data[offset..offset+len], shape)
    }
    fn weight_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i32_as_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i32> {
        TensorView::from_bytes_i32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i64_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i64_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i32_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_u8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_f16(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_f16(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8_raw(&self, offset: usize, len: usize) -> &'a [u8] {
        &self.data[offset..offset+len]
    }

    // Inference Entry Point
    pub fn forward(&self, x: TensorView<'a>) -> TensorView<'static> {
        let mut ws = PpocrRecWorkspace::new();
        let res = self.forward_with_workspace(&mut ws, x);
        res.to_owned()
    }
    pub fn forward_with_workspace<'w>(&self, ws: &'w mut PpocrRecWorkspace, x: TensorView<'w>) -> TensorView<'w> {
        let (fetch_name_0) = self.run_chunk_0(ws, x);
        fetch_name_0
    }
}
