// Auto-generated by lele_compiler
#![allow(non_snake_case)]
#![allow(unused_variables)]
#![allow(dead_code)]
#![allow(unused_parens)]
#![allow(unused_mut)]
#![allow(unused_imports)]
#![allow(clippy::too_many_arguments)]
use lele::tensor::TensorView;
use lele::kernels::*;


#[derive(Default)]
pub struct PpocrDetWorkspace {
    pub buf_0: Vec<f32>,
    pub buf_1: Vec<f32>,
    pub buf_2: Vec<f32>,
    pub buf_3: Vec<f32>,
    pub buf_4: Vec<f32>,
    pub buf_5: Vec<f32>,
    pub buf_6: Vec<f32>,
    pub buf_7: Vec<f32>,
    pub buf_8: Vec<f32>,
    pub buf_9: Vec<f32>,
    pub buf_10: Vec<f32>,
    pub buf_11: Vec<f32>,
}
impl PpocrDetWorkspace {
    pub fn new() -> Self {
        Self::default()
    }
}

pub struct PpocrDet<'a> {
    data: &'a [u8],
    _phantom: std::marker::PhantomData<&'a ()>,
    #[cfg(target_arch = "aarch64")]
    prepared_weights_cache: std::cell::RefCell<std::collections::HashMap<(usize, usize), std::sync::Arc<lele::kernels::PreparedWeightsArm>>>,
}

impl<'a> PpocrDet<'a> {
    pub fn new(data: &'a [u8]) -> Self {
        Self {
            data,
            _phantom: std::marker::PhantomData,
            #[cfg(target_arch = "aarch64")]
            prepared_weights_cache: std::cell::RefCell::new(std::collections::HashMap::new()),
        }
    }
fn conv1d_relu<'c, 'd>(
    &self,
    input: lele::tensor::TensorView<'c>,
    weight: lele::tensor::TensorView<'c>,
    bias: Option<&lele::tensor::TensorView<'c>>,
    stride: usize,
    dilation: usize,
    groups: usize,
    padding: usize,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::conv1d_fused(
        &input,
        &weight,
        bias,
        &[dilation as i64],
        groups as i64,
        &[padding as i64, padding as i64],
        &[stride as i64],
        true,
        output_buf,
    )
}
fn layer_norm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    scale: lele::tensor::TensorView<'c>,
    bias: lele::tensor::TensorView<'c>,
    epsilon: lele::tensor::TensorView<'c>,
    _two: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    let eps = epsilon.data.first().cloned().unwrap_or(1e-5);
    lele::kernels::layer_norm(input, &scale, &bias, -1, eps, output_buf)
}
fn linear_quantized<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, false, output_buf,
    )
}

fn linear_quantized_relu<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    lele::kernels::fused_quantized_linear(
        input, &weight_int8, &weight_scale, &weight_zero, &bias, true, output_buf,
    )
}

#[cfg(target_arch = "aarch64")]
fn linear_quantized_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        false,
        output_buf,
    )
}

/// ARM-optimized quantized linear + ReLU with pre-packed weights.
/// Uses fused DynQuant+GEMM: eliminates f32 intermediate buffer, per-call u8
/// allocation, and separate f32→u8 conversion pass.
#[cfg(target_arch = "aarch64")]
fn linear_quantized_relu_arm<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_b = weight_zero.data.first().map(|&v| v as u8);

    lele::kernels::fused_dq_gemm_prepared_arm(
        input,
        &pw,
        zp_b,
        &weight_scale,
        Some(&bias),
        true,
        output_buf,
    )
}

/// ARM-optimized MatMulInteger with pre-packed weight cache.
/// Used for unfused MatMulInteger nodes where B is a static model weight.
/// Eliminates: per-call B packing, B u8→f32→u8 roundtrip, heap alloc.
#[cfg(target_arch = "aarch64")]
fn mat_mul_integer_arm<'c, 'd>(
    &self,
    a: &lele::tensor::TensorView<'c, f32>,
    weight_offset: usize,
    weight_len: usize,
    weight_k: usize,
    weight_n: usize,
    a_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    b_zero_point: Option<&lele::tensor::TensorView<'c, f32>>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let pw = self.get_prepared_weight(weight_offset, weight_len, weight_k, weight_n);
    let zp_a = a_zero_point.and_then(|z| z.data.first().cloned());
    let zp_b = b_zero_point.and_then(|z| z.data.first()).map(|&v| v as u8);

    lele::kernels::mat_mul_integer_prepared_arm(a, &pw, zp_a, zp_b, None, None, false, output_buf)
}

// Helper for pre-quantized inputs (used in attention where input is already quantized)
#[inline]
fn linear_quantized_prequant<'c, 'd>(
    &self,
    input_quantized: &lele::tensor::TensorView<'c, f32>,
    input_scale: &lele::tensor::TensorView<'c, f32>,
    input_zero_point: &lele::tensor::TensorView<'c, f32>,
    weight_int8: lele::tensor::TensorView<'c, f32>,
    weight_scale: lele::tensor::TensorView<'c, f32>,
    weight_zero: lele::tensor::TensorView<'c, f32>,
    bias: lele::tensor::TensorView<'c, f32>,
    output_buf: &'d mut Vec<f32>,
    scale_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d, f32> {
    let combined_scale = lele::kernels::mul(input_scale, &weight_scale, scale_buf);

    // FUSED: MatMul + Scale + Bias in one operation
    lele::kernels::mat_mul_integer_with_scale_bias(
        input_quantized,
        &weight_int8,
        Some(input_zero_point),
        Some(&weight_zero),
        Some(&combined_scale),
        Some(&bias),
        output_buf,
    )
}
fn linear<'c, 'd>(
    &self,
    input: &lele::tensor::TensorView<'c>,
    weight: &lele::tensor::TensorView<'c>,
    bias: &lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    lele::kernels::matmul_fused_add(input, weight, bias, output_buf)
}

fn embedding_concat<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: f32,
    weight: lele::tensor::TensorView<'c>,
    output_buf: &'d mut Vec<f32>,
) -> lele::tensor::TensorView<'d> {
    // ConstantOfShape + Concat pattern
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

fn embedding_concat_i64<'c, 'd>(
    &self,
    shape: &lele::tensor::TensorView<'c, i64>,
    value: i64,
    weight: lele::tensor::TensorView<'c, i64>,
    output_buf: &'d mut Vec<i64>,
) -> lele::tensor::TensorView<'d, i64> {
    // ConstantOfShape + Concat pattern (i64)
    // shape defines the shape of the constant tensor filled with `value`
    // Then concatenate weight and the constant along axis 0
    let const_shape: Vec<usize> = shape.data.iter().map(|&x| x as usize).collect();
    let const_len: usize = const_shape.iter().product();

    output_buf.clear();
    output_buf.reserve(weight.data.len() + const_len);
    output_buf.extend_from_slice(&weight.data);
    output_buf.resize(weight.data.len() + const_len, value);

    let mut out_shape = weight.shape.to_vec();
    out_shape[0] += const_shape[0];

    lele::tensor::TensorView {
        data: std::borrow::Cow::Borrowed(output_buf),
        shape: std::borrow::Cow::Owned(out_shape),
    }
}

    #[inline(never)]
    fn run_chunk_0<'w>(&self, ws: &'w mut PpocrDetWorkspace, helper_constant_40: TensorView<'w, f32>, x: TensorView<'w, f32>) -> TensorView<'static, f32> {
        let p2o_pd_op_relu_0_0 = lele::kernels::conv2d_fused(&x, &self.weight_f32(0, 1728, &[16, 3, 3, 3]), Some(&self.weight_f32(1694256, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], true, &mut ws.buf_1);
        let p2o_pd_op_relu_1_0 = lele::kernels::conv2d_fused(&p2o_pd_op_relu_0_0, &self.weight_f32(1728, 2048, &[8, 16, 2, 2]), Some(&self.weight_f32(1694320, 32, &[8])), &[1, 1], 1, &[0, 0, 1, 1], &[1, 1], true, &mut ws.buf_3);
        let p2o_pd_op_relu_2_0 = lele::kernels::conv2d_fused(&p2o_pd_op_relu_1_0, &self.weight_f32(3776, 2048, &[16, 8, 2, 2]), Some(&self.weight_f32(1694352, 64, &[16])), &[1, 1], 1, &[0, 0, 1, 1], &[1, 1], true, &mut ws.buf_5);
        let p2o_pd_op_pool2d_0_0 = lele::kernels::max_pool2d(&p2o_pd_op_relu_0_0, &[2, 2], &[1, 1], &[0, 0, 1, 1], &[], false, &mut ws.buf_6);
        let Concat_1 = lele::kernels::concat(&[&p2o_pd_op_pool2d_0_0, &p2o_pd_op_relu_2_0], 1, &mut ws.buf_0);
        let p2o_pd_op_relu_3_0 = lele::kernels::conv2d_fused(&Concat_1, &self.weight_f32(5824, 18432, &[16, 32, 3, 3]), Some(&self.weight_f32(1694416, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[2, 2], true, &mut ws.buf_2);
        let p2o_pd_op_relu_4_0 = lele::kernels::conv2d_fused(&p2o_pd_op_relu_3_0, &self.weight_f32(24256, 2048, &[32, 16, 1, 1]), Some(&self.weight_f32(1694480, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_4);
        let p2o_pd_op_depthwise_conv2d_0_0 = lele::kernels::conv2d(&p2o_pd_op_relu_4_0, &self.weight_f32(26304, 1152, &[32, 1, 3, 3]), Some(&self.weight_f32(1694608, 128, &[32])), &[1, 1], 32, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let ReduceMean_1 = lele::kernels::reduce_mean(&p2o_pd_op_depthwise_conv2d_0_0, &[2, 3], true, &mut ws.buf_5);
        let p2o_pd_op_relu_5_0 = lele::kernels::conv2d_fused(&ReduceMean_1, &self.weight_f32(27456, 1024, &[8, 32, 1, 1]), Some(&self.weight_f32(1694736, 32, &[8])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_6);
        let p2o_pd_op_conv2d_6_0 = lele::kernels::conv2d(&p2o_pd_op_relu_5_0, &self.weight_f32(28480, 1024, &[32, 8, 1, 1]), Some(&self.weight_f32(1694768, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_hardsigmoid_0_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_6_0, 0.1666667, 0.5, &mut ws.buf_3);
        let Mul_1 = lele::kernels::mul(&p2o_pd_op_depthwise_conv2d_0_0, &p2o_pd_op_hardsigmoid_0_0, &mut ws.buf_4);
        let p2o_pd_op_conv2d_7_0 = lele::kernels::conv2d(&Mul_1, &self.weight_f32(29504, 8192, &[64, 32, 1, 1]), Some(&self.weight_f32(1694896, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let p2o_pd_op_gelu_0_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_7_0, &mut ws.buf_1);
        let p2o_pd_op_conv2d_8_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_0_0, &self.weight_f32(37744, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(1695152, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let Add_23 = lele::kernels::add(&Mul_1, &p2o_pd_op_conv2d_8_0, &mut ws.buf_8);
        let p2o_pd_op_depthwise_conv2d_1_0 = lele::kernels::conv2d(&Add_23, &self.weight_f32(45936, 1152, &[32, 1, 3, 3]), Some(&self.weight_f32(1695280, 128, &[32])), &[1, 1], 32, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_conv2d_9_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_1_0, &self.weight_f32(47088, 8192, &[64, 32, 1, 1]), Some(&self.weight_f32(1695408, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_gelu_1_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_9_0, &mut ws.buf_4);
        let p2o_pd_op_conv2d_10_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_1_0, &self.weight_f32(55280, 8192, &[32, 64, 1, 1]), Some(&self.weight_f32(1695664, 128, &[32])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_33 = lele::kernels::add(&p2o_pd_op_depthwise_conv2d_1_0, &p2o_pd_op_conv2d_10_0, &mut ws.buf_8);
        let p2o_pd_op_depthwise_conv2d_2_0 = lele::kernels::conv2d(&Add_33, &self.weight_f32(63472, 1152, &[32, 1, 3, 3]), Some(&self.weight_f32(1695792, 128, &[32])), &[1, 1], 32, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_6);
        let p2o_pd_op_conv2d_11_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_2_0, &self.weight_f32(64624, 8192, &[64, 32, 1, 1]), Some(&self.weight_f32(1695920, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_gelu_2_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_11_0, &mut ws.buf_5);
        let p2o_pd_op_conv2d_12_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_2_0, &self.weight_f32(72816, 12288, &[48, 64, 1, 1]), Some(&self.weight_f32(1696176, 192, &[48])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_depthwise_conv2d_3_0 = lele::kernels::conv2d(&p2o_pd_op_conv2d_12_0, &self.weight_f32(85104, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(1696368, 192, &[48])), &[1, 1], 48, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let ReduceMean_3 = lele::kernels::reduce_mean(&p2o_pd_op_depthwise_conv2d_3_0, &[2, 3], true, &mut ws.buf_0);
        let p2o_pd_op_relu_6_0 = lele::kernels::conv2d_fused(&ReduceMean_3, &self.weight_f32(86832, 2304, &[12, 48, 1, 1]), Some(&self.weight_f32(1696560, 48, &[12])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_2);
        let p2o_pd_op_conv2d_14_0 = lele::kernels::conv2d(&p2o_pd_op_relu_6_0, &self.weight_f32(89136, 2304, &[48, 12, 1, 1]), Some(&self.weight_f32(1696608, 192, &[48])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_hardsigmoid_1_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_14_0, 0.1666667, 0.5, &mut ws.buf_4);
        let Mul_12 = lele::kernels::mul(&p2o_pd_op_depthwise_conv2d_3_0, &p2o_pd_op_hardsigmoid_1_0, &mut ws.buf_5);
        let p2o_pd_op_conv2d_15_0 = lele::kernels::conv2d(&Mul_12, &self.weight_f32(91440, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(1696800, 384, &[96])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_gelu_3_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_15_0, &mut ws.buf_4);
        let p2o_pd_op_conv2d_16_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_3_0, &self.weight_f32(109872, 18432, &[48, 96, 1, 1]), Some(&self.weight_f32(1697184, 192, &[48])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_55 = lele::kernels::add(&Mul_12, &p2o_pd_op_conv2d_16_0, &mut ws.buf_9);
        let p2o_pd_op_depthwise_conv2d_4_0 = lele::kernels::conv2d(&Add_55, &self.weight_f32(128304, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(1697376, 192, &[48])), &[1, 1], 48, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_conv2d_17_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_4_0, &self.weight_f32(130032, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(1697568, 384, &[96])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let p2o_pd_op_gelu_4_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_17_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_18_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_4_0, &self.weight_f32(148464, 18432, &[48, 96, 1, 1]), Some(&self.weight_f32(1697952, 192, &[48])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_65 = lele::kernels::add(&p2o_pd_op_depthwise_conv2d_4_0, &p2o_pd_op_conv2d_18_0, &mut ws.buf_9);
        let p2o_pd_op_depthwise_conv2d_5_0 = lele::kernels::conv2d(&Add_65, &self.weight_f32(166896, 1728, &[48, 1, 3, 3]), Some(&self.weight_f32(1698144, 192, &[48])), &[1, 1], 48, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_2);
        let p2o_pd_op_conv2d_19_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_5_0, &self.weight_f32(168624, 18432, &[96, 48, 1, 1]), Some(&self.weight_f32(1698336, 384, &[96])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_gelu_5_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_19_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_20_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_5_0, &self.weight_f32(187056, 24576, &[64, 96, 1, 1]), Some(&self.weight_f32(1698720, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_depthwise_conv2d_6_0 = lele::kernels::conv2d(&p2o_pd_op_conv2d_20_0, &self.weight_f32(211632, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(1698976, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let ReduceMean_5 = lele::kernels::reduce_mean(&p2o_pd_op_depthwise_conv2d_6_0, &[2, 3], true, &mut ws.buf_1);
        let p2o_pd_op_relu_7_0 = lele::kernels::conv2d_fused(&ReduceMean_5, &self.weight_f32(213936, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1699232, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_3);
        let p2o_pd_op_conv2d_22_0 = lele::kernels::conv2d(&p2o_pd_op_relu_7_0, &self.weight_f32(218032, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1699296, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_hardsigmoid_2_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_22_0, 0.1666667, 0.5, &mut ws.buf_5);
        let Mul_23 = lele::kernels::mul(&p2o_pd_op_depthwise_conv2d_6_0, &p2o_pd_op_hardsigmoid_2_0, &mut ws.buf_2);
        let p2o_pd_op_conv2d_23_0 = lele::kernels::conv2d(&Mul_23, &self.weight_f32(222128, 32768, &[128, 64, 1, 1]), Some(&self.weight_f32(1699552, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_gelu_6_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_23_0, &mut ws.buf_5);
        let p2o_pd_op_conv2d_24_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_6_0, &self.weight_f32(254896, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(1700064, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_87 = lele::kernels::add(&Mul_23, &p2o_pd_op_conv2d_24_0, &mut ws.buf_10);
        let p2o_pd_op_depthwise_conv2d_7_0 = lele::kernels::conv2d(&Add_87, &self.weight_f32(287664, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(1700320, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let p2o_pd_op_conv2d_25_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_7_0, &self.weight_f32(289968, 32768, &[128, 64, 1, 1]), Some(&self.weight_f32(1700576, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_gelu_7_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_25_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_26_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_7_0, &self.weight_f32(322736, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(1701088, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_97 = lele::kernels::add(&p2o_pd_op_depthwise_conv2d_7_0, &p2o_pd_op_conv2d_26_0, &mut ws.buf_10);
        let p2o_pd_op_depthwise_conv2d_8_0 = lele::kernels::conv2d(&Add_97, &self.weight_f32(355504, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(1701344, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_3);
        let ReduceMean_7 = lele::kernels::reduce_mean(&p2o_pd_op_depthwise_conv2d_8_0, &[2, 3], true, &mut ws.buf_0);
        let p2o_pd_op_relu_8_0 = lele::kernels::conv2d_fused(&ReduceMean_7, &self.weight_f32(357808, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1701600, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_2);
        let p2o_pd_op_conv2d_28_0 = lele::kernels::conv2d(&p2o_pd_op_relu_8_0, &self.weight_f32(361904, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1701664, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_hardsigmoid_3_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_28_0, 0.1666667, 0.5, &mut ws.buf_1);
        let Mul_31 = lele::kernels::mul(&p2o_pd_op_depthwise_conv2d_8_0, &p2o_pd_op_hardsigmoid_3_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_29_0 = lele::kernels::conv2d(&Mul_31, &self.weight_f32(366000, 32768, &[128, 64, 1, 1]), Some(&self.weight_f32(1701920, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let p2o_pd_op_gelu_8_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_29_0, &mut ws.buf_1);
        let p2o_pd_op_conv2d_30_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_8_0, &self.weight_f32(398768, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(1702432, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let Add_111 = lele::kernels::add(&Mul_31, &p2o_pd_op_conv2d_30_0, &mut ws.buf_10);
        let p2o_pd_op_depthwise_conv2d_9_0 = lele::kernels::conv2d(&Add_111, &self.weight_f32(431536, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(1702688, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_conv2d_31_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_9_0, &self.weight_f32(433840, 32768, &[128, 64, 1, 1]), Some(&self.weight_f32(1702944, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_gelu_9_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_31_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_32_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_9_0, &self.weight_f32(466608, 32768, &[64, 128, 1, 1]), Some(&self.weight_f32(1703456, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_121 = lele::kernels::add(&p2o_pd_op_depthwise_conv2d_9_0, &p2o_pd_op_conv2d_32_0, &mut ws.buf_10);
        let p2o_pd_op_depthwise_conv2d_10_0 = lele::kernels::conv2d(&Add_121, &self.weight_f32(499376, 2304, &[64, 1, 3, 3]), Some(&self.weight_f32(1703712, 256, &[64])), &[1, 1], 64, &[1, 1, 1, 1], &[2, 2], &mut ws.buf_2);
        let p2o_pd_op_conv2d_33_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_10_0, &self.weight_f32(501680, 32768, &[128, 64, 1, 1]), Some(&self.weight_f32(1703968, 512, &[128])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_gelu_10_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_33_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_34_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_10_0, &self.weight_f32(534448, 81920, &[160, 128, 1, 1]), Some(&self.weight_f32(1704480, 640, &[160])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_depthwise_conv2d_11_0 = lele::kernels::conv2d(&p2o_pd_op_conv2d_34_0, &self.weight_f32(616368, 5760, &[160, 1, 3, 3]), Some(&self.weight_f32(1705120, 640, &[160])), &[1, 1], 160, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_7);
        let ReduceMean_9 = lele::kernels::reduce_mean(&p2o_pd_op_depthwise_conv2d_11_0, &[2, 3], true, &mut ws.buf_1);
        let p2o_pd_op_relu_9_0 = lele::kernels::conv2d_fused(&ReduceMean_9, &self.weight_f32(622128, 25600, &[40, 160, 1, 1]), Some(&self.weight_f32(1705760, 160, &[40])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_4);
        let p2o_pd_op_conv2d_36_0 = lele::kernels::conv2d(&p2o_pd_op_relu_9_0, &self.weight_f32(647728, 25600, &[160, 40, 1, 1]), Some(&self.weight_f32(1705920, 640, &[160])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_hardsigmoid_4_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_36_0, 0.1666667, 0.5, &mut ws.buf_5);
        let Mul_42 = lele::kernels::mul(&p2o_pd_op_depthwise_conv2d_11_0, &p2o_pd_op_hardsigmoid_4_0, &mut ws.buf_2);
        let p2o_pd_op_conv2d_37_0 = lele::kernels::conv2d(&Mul_42, &self.weight_f32(673328, 204800, &[320, 160, 1, 1]), Some(&self.weight_f32(1706560, 1280, &[320])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_gelu_11_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_37_0, &mut ws.buf_5);
        let p2o_pd_op_conv2d_38_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_11_0, &self.weight_f32(878128, 204800, &[160, 320, 1, 1]), Some(&self.weight_f32(1707840, 640, &[160])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_143 = lele::kernels::add(&Mul_42, &p2o_pd_op_conv2d_38_0, &mut ws.buf_11);
        let p2o_pd_op_depthwise_conv2d_12_0 = lele::kernels::conv2d(&Add_143, &self.weight_f32(1082928, 5760, &[160, 1, 3, 3]), Some(&self.weight_f32(1708480, 640, &[160])), &[1, 1], 160, &[1, 1, 1, 1], &[1, 1], &mut ws.buf_1);
        let p2o_pd_op_conv2d_39_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_12_0, &self.weight_f32(1088688, 204800, &[320, 160, 1, 1]), Some(&self.weight_f32(1709120, 1280, &[320])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_gelu_12_0 = lele::kernels::gelu(&p2o_pd_op_conv2d_39_0, &mut ws.buf_6);
        let p2o_pd_op_conv2d_40_0 = lele::kernels::conv2d(&p2o_pd_op_gelu_12_0, &self.weight_f32(1293488, 204800, &[160, 320, 1, 1]), Some(&self.weight_f32(1710400, 640, &[160])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_7);
        let Add_153 = lele::kernels::add(&p2o_pd_op_depthwise_conv2d_12_0, &p2o_pd_op_conv2d_40_0, &mut ws.buf_11);
        let p2o_pd_op_conv2d_41_0 = lele::kernels::conv2d(&Add_153, &self.weight_f32(1498288, 40960, &[64, 160, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_pool2d_1_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_41_0, &mut ws.buf_0);
        let p2o_pd_op_relu_10_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_1_0, &self.weight_f32(1539248, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1711040, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_2);
        let p2o_pd_op_conv2d_43_0 = lele::kernels::conv2d(&p2o_pd_op_relu_10_0, &self.weight_f32(1543344, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1711104, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_hardsigmoid_5_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_43_0, 0.2, 0.5, &mut ws.buf_1);
        let Mul_50 = lele::kernels::mul(&p2o_pd_op_conv2d_41_0, &p2o_pd_op_hardsigmoid_5_0, &mut ws.buf_6);
        let Add_159 = lele::kernels::add(&p2o_pd_op_conv2d_41_0, &Mul_50, &mut ws.buf_7);
        let p2o_pd_op_conv2d_44_0 = lele::kernels::conv2d(&Add_121, &self.weight_f32(1547440, 16384, &[64, 64, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_pool2d_2_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_44_0, &mut ws.buf_3);
        let p2o_pd_op_relu_11_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_2_0, &self.weight_f32(1563824, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1711360, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_5);
        let p2o_pd_op_conv2d_46_0 = lele::kernels::conv2d(&p2o_pd_op_relu_11_0, &self.weight_f32(1567920, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1711424, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_1);
        let p2o_pd_op_hardsigmoid_6_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_46_0, 0.2, 0.5, &mut ws.buf_4);
        let Mul_52 = lele::kernels::mul(&p2o_pd_op_conv2d_44_0, &p2o_pd_op_hardsigmoid_6_0, &mut ws.buf_6);
        let Add_165 = lele::kernels::add(&p2o_pd_op_conv2d_44_0, &Mul_52, &mut ws.buf_10);
        let p2o_pd_op_conv2d_47_0 = lele::kernels::conv2d(&Add_65, &self.weight_f32(1572016, 12288, &[64, 48, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_pool2d_3_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_47_0, &mut ws.buf_2);
        let p2o_pd_op_relu_12_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_3_0, &self.weight_f32(1584304, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1711680, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_1);
        let p2o_pd_op_conv2d_49_0 = lele::kernels::conv2d(&p2o_pd_op_relu_12_0, &self.weight_f32(1588400, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1711744, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_hardsigmoid_7_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_49_0, 0.2, 0.5, &mut ws.buf_0);
        let Mul_54 = lele::kernels::mul(&p2o_pd_op_conv2d_47_0, &p2o_pd_op_hardsigmoid_7_0, &mut ws.buf_6);
        let Add_171 = lele::kernels::add(&p2o_pd_op_conv2d_47_0, &Mul_54, &mut ws.buf_9);
        let p2o_pd_op_conv2d_50_0 = lele::kernels::conv2d(&Add_33, &self.weight_f32(1592496, 8192, &[64, 32, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_2);
        let p2o_pd_op_pool2d_4_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_50_0, &mut ws.buf_5);
        let p2o_pd_op_relu_13_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_4_0, &self.weight_f32(1600688, 4096, &[16, 64, 1, 1]), Some(&self.weight_f32(1712000, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_4);
        let p2o_pd_op_conv2d_52_0 = lele::kernels::conv2d(&p2o_pd_op_relu_13_0, &self.weight_f32(1604784, 4096, &[64, 16, 1, 1]), Some(&self.weight_f32(1712064, 256, &[64])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_0);
        let p2o_pd_op_hardsigmoid_8_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_52_0, 0.2, 0.5, &mut ws.buf_3);
        let Mul_56 = lele::kernels::mul(&p2o_pd_op_conv2d_50_0, &p2o_pd_op_hardsigmoid_8_0, &mut ws.buf_6);
        let Add_177 = lele::kernels::add(&p2o_pd_op_conv2d_50_0, &Mul_56, &mut ws.buf_8);
        let p2o_pd_op_nearest_interp_0_0 = lele::kernels::resize_nearest(&Add_159, Some(&self.weight_f32(1608880, 16, &[4]).data), None, "asymmetric", &mut ws.buf_5);
        let Add_179 = lele::kernels::add(&Add_165, &p2o_pd_op_nearest_interp_0_0, &mut ws.buf_1);
        let p2o_pd_op_nearest_interp_1_0 = lele::kernels::resize_nearest(&Add_179, Some(&self.weight_f32(1608880, 16, &[4]).data), None, "asymmetric", &mut ws.buf_4);
        let Add_181 = lele::kernels::add(&Add_171, &p2o_pd_op_nearest_interp_1_0, &mut ws.buf_0);
        let p2o_pd_op_nearest_interp_2_0 = lele::kernels::resize_nearest(&Add_181, Some(&self.weight_f32(1608880, 16, &[4]).data), None, "asymmetric", &mut ws.buf_3);
        let Add_183 = lele::kernels::add(&Add_177, &p2o_pd_op_nearest_interp_2_0, &mut ws.buf_2);
        let p2o_pd_op_depthwise_conv2d_13_0 = lele::kernels::conv2d(&Add_159, &self.weight_f32(1608896, 6400, &[64, 1, 5, 5]), Some(&self.weight_f32(1712320, 256, &[64])), &[1, 1], 64, &[2, 2, 2, 2], &[1, 1], &mut ws.buf_6);
        let p2o_pd_op_conv2d_53_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_13_0, &self.weight_f32(1615296, 4096, &[16, 64, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_pool2d_5_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_53_0, &mut ws.buf_10);
        let p2o_pd_op_relu_14_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_5_0, &self.weight_f32(1619392, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(1712576, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_9);
        let p2o_pd_op_conv2d_55_0 = lele::kernels::conv2d(&p2o_pd_op_relu_14_0, &self.weight_f32(1619648, 256, &[16, 4, 1, 1]), Some(&self.weight_f32(1712592, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_hardsigmoid_9_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_55_0, 0.2, 0.5, &mut ws.buf_7);
        let Mul_58 = lele::kernels::mul(&p2o_pd_op_conv2d_53_0, &p2o_pd_op_hardsigmoid_9_0, &mut ws.buf_6);
        let Add_191 = lele::kernels::add(&p2o_pd_op_conv2d_53_0, &Mul_58, &mut ws.buf_8);
        let p2o_pd_op_depthwise_conv2d_14_0 = lele::kernels::conv2d(&Add_179, &self.weight_f32(1619904, 6400, &[64, 1, 5, 5]), Some(&self.weight_f32(1712656, 256, &[64])), &[1, 1], 64, &[2, 2, 2, 2], &[1, 1], &mut ws.buf_10);
        let p2o_pd_op_conv2d_56_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_14_0, &self.weight_f32(1626304, 4096, &[16, 64, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_pool2d_6_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_56_0, &mut ws.buf_9);
        let p2o_pd_op_relu_15_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_6_0, &self.weight_f32(1630400, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(1712912, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_7);
        let p2o_pd_op_conv2d_58_0 = lele::kernels::conv2d(&p2o_pd_op_relu_15_0, &self.weight_f32(1630656, 256, &[16, 4, 1, 1]), Some(&self.weight_f32(1712928, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_hardsigmoid_10_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_58_0, 0.2, 0.5, &mut ws.buf_1);
        let Mul_60 = lele::kernels::mul(&p2o_pd_op_conv2d_56_0, &p2o_pd_op_hardsigmoid_10_0, &mut ws.buf_6);
        let Add_199 = lele::kernels::add(&p2o_pd_op_conv2d_56_0, &Mul_60, &mut ws.buf_10);
        let p2o_pd_op_depthwise_conv2d_15_0 = lele::kernels::conv2d(&Add_181, &self.weight_f32(1630912, 6400, &[64, 1, 5, 5]), Some(&self.weight_f32(1712992, 256, &[64])), &[1, 1], 64, &[2, 2, 2, 2], &[1, 1], &mut ws.buf_9);
        let p2o_pd_op_conv2d_59_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_15_0, &self.weight_f32(1637312, 4096, &[16, 64, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_pool2d_7_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_59_0, &mut ws.buf_7);
        let p2o_pd_op_relu_16_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_7_0, &self.weight_f32(1641408, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(1713248, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_1);
        let p2o_pd_op_conv2d_61_0 = lele::kernels::conv2d(&p2o_pd_op_relu_16_0, &self.weight_f32(1641664, 256, &[16, 4, 1, 1]), Some(&self.weight_f32(1713264, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_4);
        let p2o_pd_op_hardsigmoid_11_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_61_0, 0.2, 0.5, &mut ws.buf_0);
        let Mul_62 = lele::kernels::mul(&p2o_pd_op_conv2d_59_0, &p2o_pd_op_hardsigmoid_11_0, &mut ws.buf_6);
        let Add_207 = lele::kernels::add(&p2o_pd_op_conv2d_59_0, &Mul_62, &mut ws.buf_9);
        let p2o_pd_op_depthwise_conv2d_16_0 = lele::kernels::conv2d(&Add_183, &self.weight_f32(1641920, 6400, &[64, 1, 5, 5]), Some(&self.weight_f32(1713328, 256, &[64])), &[1, 1], 64, &[2, 2, 2, 2], &[1, 1], &mut ws.buf_7);
        let p2o_pd_op_conv2d_62_0 = lele::kernels::conv2d(&p2o_pd_op_depthwise_conv2d_16_0, &self.weight_f32(1648320, 4096, &[16, 64, 1, 1]), None, &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_5);
        let p2o_pd_op_pool2d_8_0 = lele::kernels::global_average_pool(&p2o_pd_op_conv2d_62_0, &mut ws.buf_1);
        let p2o_pd_op_relu_17_0 = lele::kernels::conv2d_fused(&p2o_pd_op_pool2d_8_0, &self.weight_f32(1652416, 256, &[4, 16, 1, 1]), Some(&self.weight_f32(1713584, 16, &[4])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], true, &mut ws.buf_0);
        let p2o_pd_op_conv2d_64_0 = lele::kernels::conv2d(&p2o_pd_op_relu_17_0, &self.weight_f32(1652672, 256, &[16, 4, 1, 1]), Some(&self.weight_f32(1713600, 64, &[16])), &[1, 1], 1, &[0, 0, 0, 0], &[1, 1], &mut ws.buf_3);
        let p2o_pd_op_hardsigmoid_12_0 = lele::kernels::hard_sigmoid(&p2o_pd_op_conv2d_64_0, 0.2, 0.5, &mut ws.buf_2);
        let Mul_64 = lele::kernels::mul(&p2o_pd_op_conv2d_62_0, &p2o_pd_op_hardsigmoid_12_0, &mut ws.buf_6);
        let Add_215 = lele::kernels::add(&p2o_pd_op_conv2d_62_0, &Mul_64, &mut ws.buf_7);
        let p2o_pd_op_nearest_interp_3_0 = lele::kernels::resize_nearest(&Add_191, Some(&self.weight_f32(1652928, 16, &[4]).data), None, "asymmetric", &mut ws.buf_1);
        let p2o_pd_op_nearest_interp_4_0 = lele::kernels::resize_nearest(&Add_199, Some(&self.weight_f32(1652944, 16, &[4]).data), None, "asymmetric", &mut ws.buf_4);
        let p2o_pd_op_nearest_interp_5_0 = lele::kernels::resize_nearest(&Add_207, Some(&self.weight_f32(1608880, 16, &[4]).data), None, "asymmetric", &mut ws.buf_0);
        let Concat_3 = lele::kernels::concat(&[&p2o_pd_op_nearest_interp_3_0, &p2o_pd_op_nearest_interp_4_0, &p2o_pd_op_nearest_interp_5_0, &Add_215], 1, &mut ws.buf_3);
        let p2o_pd_op_relu_18_0 = lele::kernels::conv2d_fused(&Concat_3, &self.weight_f32(1652960, 36864, &[16, 64, 3, 3]), Some(&self.weight_f32(1713664, 64, &[16])), &[1, 1], 1, &[1, 1, 1, 1], &[1, 1], true, &mut ws.buf_5);
        let ConvTranspose_1 = lele::kernels::conv_transpose(&p2o_pd_op_relu_18_0, &self.weight_f32(1689824, 4096, &[16, 16, 2, 2]), None, &[1, 1], 1, &[0, 0, 0, 0], &[2, 2], &mut ws.buf_6);
        let Add_219 = lele::kernels::add(&ConvTranspose_1, &self.weight_f32(1693920, 64, &[1, 16, 1, 1]), &mut ws.buf_8);
        let p2o_pd_op_relu_19_0 = lele::kernels::relu(&Add_219, &mut ws.buf_9);
        let ConvTranspose_3 = lele::kernels::conv_transpose(&p2o_pd_op_relu_19_0, &self.weight_f32(1693984, 256, &[16, 1, 2, 2]), None, &[1, 1], 1, &[0, 0, 0, 0], &[2, 2], &mut ws.buf_0);
        let Add_221 = lele::kernels::add(&ConvTranspose_3, &self.weight_f32(1694240, 4, &[1, 1, 1, 1]), &mut ws.buf_1);
        let fetch_name_0 = lele::kernels::sigmoid(&Add_221, &mut ws.buf_2);
        unsafe { fetch_name_0.detach_or_own() }
    }


    #[cfg(target_arch = "aarch64")]
    fn get_prepared_weight(&self, offset: usize, len: usize, k: usize, n: usize) -> std::sync::Arc<lele::kernels::PreparedWeightsArm> {
        let key = (offset, len);
        {
            let cache = self.prepared_weights_cache.borrow();
            if let Some(pw) = cache.get(&key) {
                return pw.clone();
            }
        }
        let raw_bytes = &self.data[offset..offset+len];
        let pw = std::sync::Arc::new(lele::kernels::prepare_weights_arm(raw_bytes, k, n));
        self.prepared_weights_cache.borrow_mut().insert(key, pw.clone());
        pw
    }
    fn weight_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'a, f32> {
        TensorView::from_bytes_f32(&self.data[offset..offset+len], shape)
    }
    fn weight_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_i64(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i64> {
        TensorView::from_bytes_i32_as_i64(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, i32> {
        TensorView::from_bytes_i32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i64_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i64_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i32_f32(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i32_as_f32(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_u8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_i8(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_i8(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_f16(&self, offset: usize, len: usize, shape: &'a [usize]) -> TensorView<'static, f32> {
        TensorView::from_bytes_f16(&self.data[offset..offset+len], shape.to_vec())
    }
    fn weight_u8_raw(&self, offset: usize, len: usize) -> &'a [u8] {
        &self.data[offset..offset+len]
    }

    // Inference Entry Point
    pub fn forward(&self, x: TensorView<'a>) -> TensorView<'static> {
        let mut ws = PpocrDetWorkspace::new();
        let res = self.forward_with_workspace(&mut ws, x);
        res.to_owned()
    }
    pub fn forward_with_workspace<'w>(&self, ws: &'w mut PpocrDetWorkspace, x: TensorView<'w>) -> TensorView<'w> {
        let (fetch_name_0) = self.run_chunk_0(ws, lele::tensor::TensorView::empty(), x);
        fetch_name_0
    }
}
