// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttributeProto {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "21")]
    pub ref_attr_name: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(enumeration = "attribute_proto::AttributeType", tag = "20")]
    pub r#type: i32,
    #[prost(float, tag = "2")]
    pub f: f32,
    #[prost(int64, tag = "3")]
    pub i: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub s: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub t: ::core::option::Option<TensorProto>,
    #[prost(message, optional, tag = "6")]
    pub g: ::core::option::Option<GraphProto>,
    #[prost(message, optional, tag = "22")]
    pub sparse_tensor: ::core::option::Option<SparseTensorProto>,
    #[prost(message, optional, tag = "14")]
    pub tp: ::core::option::Option<TypeProto>,
    #[prost(float, repeated, tag = "7")]
    pub floats: ::prost::alloc::vec::Vec<f32>,
    #[prost(int64, repeated, tag = "8")]
    pub ints: ::prost::alloc::vec::Vec<i64>,
    #[prost(bytes = "vec", repeated, tag = "9")]
    pub strings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "10")]
    pub tensors: ::prost::alloc::vec::Vec<TensorProto>,
    #[prost(message, repeated, tag = "11")]
    pub graphs: ::prost::alloc::vec::Vec<GraphProto>,
    #[prost(message, repeated, tag = "23")]
    pub sparse_tensors: ::prost::alloc::vec::Vec<SparseTensorProto>,
    #[prost(message, repeated, tag = "15")]
    pub type_protos: ::prost::alloc::vec::Vec<TypeProto>,
}
/// Nested message and enum types in `AttributeProto`.
pub mod attribute_proto {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AttributeType {
        Undefined = 0,
        Float = 1,
        Int = 2,
        String = 3,
        Tensor = 4,
        Graph = 5,
        SparseTensor = 11,
        TypeProto = 13,
        Floats = 6,
        Ints = 7,
        Strings = 8,
        Tensors = 9,
        Graphs = 10,
        SparseTensors = 12,
        TypeProtos = 14,
    }
    impl AttributeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "UNDEFINED",
                Self::Float => "FLOAT",
                Self::Int => "INT",
                Self::String => "STRING",
                Self::Tensor => "TENSOR",
                Self::Graph => "GRAPH",
                Self::SparseTensor => "SPARSE_TENSOR",
                Self::TypeProto => "TYPE_PROTO",
                Self::Floats => "FLOATS",
                Self::Ints => "INTS",
                Self::Strings => "STRINGS",
                Self::Tensors => "TENSORS",
                Self::Graphs => "GRAPHS",
                Self::SparseTensors => "SPARSE_TENSORS",
                Self::TypeProtos => "TYPE_PROTOS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNDEFINED" => Some(Self::Undefined),
                "FLOAT" => Some(Self::Float),
                "INT" => Some(Self::Int),
                "STRING" => Some(Self::String),
                "TENSOR" => Some(Self::Tensor),
                "GRAPH" => Some(Self::Graph),
                "SPARSE_TENSOR" => Some(Self::SparseTensor),
                "TYPE_PROTO" => Some(Self::TypeProto),
                "FLOATS" => Some(Self::Floats),
                "INTS" => Some(Self::Ints),
                "STRINGS" => Some(Self::Strings),
                "TENSORS" => Some(Self::Tensors),
                "GRAPHS" => Some(Self::Graphs),
                "SPARSE_TENSORS" => Some(Self::SparseTensors),
                "TYPE_PROTOS" => Some(Self::TypeProtos),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValueInfoProto {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub r#type: ::core::option::Option<TypeProto>,
    #[prost(string, tag = "3")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeProto {
    #[prost(string, repeated, tag = "1")]
    pub input: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub output: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub op_type: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub overload: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub attribute: ::prost::alloc::vec::Vec<AttributeProto>,
    #[prost(string, tag = "6")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "9")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StringStringEntryProto {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorAnnotation {
    #[prost(string, tag = "1")]
    pub tensor_name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub quant_parameter_tensor_names: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphProto {
    #[prost(message, repeated, tag = "1")]
    pub node: ::prost::alloc::vec::Vec<NodeProto>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub initializer: ::prost::alloc::vec::Vec<TensorProto>,
    #[prost(message, repeated, tag = "15")]
    pub sparse_initializer: ::prost::alloc::vec::Vec<SparseTensorProto>,
    #[prost(string, tag = "10")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "11")]
    pub input: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "12")]
    pub output: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "13")]
    pub value_info: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "14")]
    pub quantization_annotation: ::prost::alloc::vec::Vec<TensorAnnotation>,
    #[prost(message, repeated, tag = "16")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorProto {
    #[prost(int64, repeated, tag = "1")]
    pub dims: ::prost::alloc::vec::Vec<i64>,
    #[prost(int32, tag = "2")]
    pub data_type: i32,
    #[prost(message, optional, tag = "3")]
    pub segment: ::core::option::Option<tensor_proto::Segment>,
    #[prost(float, repeated, tag = "4")]
    pub float_data: ::prost::alloc::vec::Vec<f32>,
    #[prost(int32, repeated, tag = "5")]
    pub int32_data: ::prost::alloc::vec::Vec<i32>,
    #[prost(bytes = "vec", repeated, tag = "6")]
    pub string_data: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(int64, repeated, tag = "7")]
    pub int64_data: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, tag = "8")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "12")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, repeated, tag = "13")]
    pub external_data: ::prost::alloc::vec::Vec<StringStringEntryProto>,
    #[prost(enumeration = "tensor_proto::DataLocation", tag = "14")]
    pub data_location: i32,
    #[prost(double, repeated, tag = "10")]
    pub double_data: ::prost::alloc::vec::Vec<f64>,
    #[prost(uint64, repeated, tag = "11")]
    pub uint64_data: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, repeated, tag = "16")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
/// Nested message and enum types in `TensorProto`.
pub mod tensor_proto {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Segment {
        #[prost(int64, tag = "1")]
        pub begin: i64,
        #[prost(int64, tag = "2")]
        pub end: i64,
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataType {
        Undefined = 0,
        Float = 1,
        Uint8 = 2,
        Int8 = 3,
        Uint16 = 4,
        Int16 = 5,
        Int32 = 6,
        Int64 = 7,
        String = 8,
        Bool = 9,
        Float16 = 10,
        Double = 11,
        Uint32 = 12,
        Uint64 = 13,
        Complex64 = 14,
        Complex128 = 15,
        /// ... truncated less common types for brevity if errors occur
        Bfloat16 = 16,
    }
    impl DataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "UNDEFINED",
                Self::Float => "FLOAT",
                Self::Uint8 => "UINT8",
                Self::Int8 => "INT8",
                Self::Uint16 => "UINT16",
                Self::Int16 => "INT16",
                Self::Int32 => "INT32",
                Self::Int64 => "INT64",
                Self::String => "STRING",
                Self::Bool => "BOOL",
                Self::Float16 => "FLOAT16",
                Self::Double => "DOUBLE",
                Self::Uint32 => "UINT32",
                Self::Uint64 => "UINT64",
                Self::Complex64 => "COMPLEX64",
                Self::Complex128 => "COMPLEX128",
                Self::Bfloat16 => "BFLOAT16",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNDEFINED" => Some(Self::Undefined),
                "FLOAT" => Some(Self::Float),
                "UINT8" => Some(Self::Uint8),
                "INT8" => Some(Self::Int8),
                "UINT16" => Some(Self::Uint16),
                "INT16" => Some(Self::Int16),
                "INT32" => Some(Self::Int32),
                "INT64" => Some(Self::Int64),
                "STRING" => Some(Self::String),
                "BOOL" => Some(Self::Bool),
                "FLOAT16" => Some(Self::Float16),
                "DOUBLE" => Some(Self::Double),
                "UINT32" => Some(Self::Uint32),
                "UINT64" => Some(Self::Uint64),
                "COMPLEX64" => Some(Self::Complex64),
                "COMPLEX128" => Some(Self::Complex128),
                "BFLOAT16" => Some(Self::Bfloat16),
                _ => None,
            }
        }
    }
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataLocation {
        Default = 0,
        External = 1,
    }
    impl DataLocation {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Default => "DEFAULT",
                Self::External => "EXTERNAL",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "DEFAULT" => Some(Self::Default),
                "EXTERNAL" => Some(Self::External),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SparseTensorProto {
    #[prost(message, optional, tag = "1")]
    pub values: ::core::option::Option<TensorProto>,
    #[prost(message, optional, tag = "2")]
    pub indices: ::core::option::Option<TensorProto>,
    #[prost(int64, repeated, tag = "3")]
    pub dims: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorShapeProto {
    #[prost(message, repeated, tag = "1")]
    pub dim: ::prost::alloc::vec::Vec<tensor_shape_proto::Dimension>,
}
/// Nested message and enum types in `TensorShapeProto`.
pub mod tensor_shape_proto {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Dimension {
        #[prost(string, tag = "3")]
        pub denotation: ::prost::alloc::string::String,
        #[prost(oneof = "dimension::Value", tags = "1, 2")]
        pub value: ::core::option::Option<dimension::Value>,
    }
    /// Nested message and enum types in `Dimension`.
    pub mod dimension {
        #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
        pub enum Value {
            #[prost(int64, tag = "1")]
            DimValue(i64),
            #[prost(string, tag = "2")]
            DimParam(::prost::alloc::string::String),
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeProto {
    #[prost(string, tag = "6")]
    pub denotation: ::prost::alloc::string::String,
    #[prost(oneof = "type_proto::Value", tags = "1, 4, 5, 9, 8")]
    pub value: ::core::option::Option<type_proto::Value>,
}
/// Nested message and enum types in `TypeProto`.
pub mod type_proto {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Tensor {
        #[prost(int32, tag = "1")]
        pub elem_type: i32,
        #[prost(message, optional, tag = "2")]
        pub shape: ::core::option::Option<super::TensorShapeProto>,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Sequence {
        #[prost(message, optional, boxed, tag = "1")]
        pub elem_type: ::core::option::Option<
            ::prost::alloc::boxed::Box<super::TypeProto>,
        >,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Map {
        #[prost(int32, tag = "1")]
        pub key_type: i32,
        #[prost(message, optional, boxed, tag = "2")]
        pub value_type: ::core::option::Option<
            ::prost::alloc::boxed::Box<super::TypeProto>,
        >,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Optional {
        #[prost(message, optional, boxed, tag = "1")]
        pub elem_type: ::core::option::Option<
            ::prost::alloc::boxed::Box<super::TypeProto>,
        >,
    }
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct SparseTensor {
        #[prost(int32, tag = "1")]
        pub elem_type: i32,
        #[prost(message, optional, tag = "2")]
        pub shape: ::core::option::Option<super::TensorShapeProto>,
    }
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        TensorType(Tensor),
        #[prost(message, tag = "4")]
        SequenceType(::prost::alloc::boxed::Box<Sequence>),
        #[prost(message, tag = "5")]
        MapType(::prost::alloc::boxed::Box<Map>),
        #[prost(message, tag = "9")]
        OptionalType(::prost::alloc::boxed::Box<Optional>),
        #[prost(message, tag = "8")]
        SparseTensorType(SparseTensor),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperatorSetIdProto {
    #[prost(string, tag = "1")]
    pub domain: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub version: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FunctionProto {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub input: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "5")]
    pub output: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "6")]
    pub attribute: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, repeated, tag = "11")]
    pub attribute_proto: ::prost::alloc::vec::Vec<AttributeProto>,
    #[prost(message, repeated, tag = "7")]
    pub node: ::prost::alloc::vec::Vec<NodeProto>,
    #[prost(string, tag = "8")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "9")]
    pub opset_import: ::prost::alloc::vec::Vec<OperatorSetIdProto>,
    #[prost(string, tag = "10")]
    pub domain: ::prost::alloc::string::String,
    #[prost(string, tag = "13")]
    pub overload: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "12")]
    pub value_info: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "14")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelProto {
    #[prost(int64, tag = "1")]
    pub ir_version: i64,
    #[prost(message, repeated, tag = "8")]
    pub opset_import: ::prost::alloc::vec::Vec<OperatorSetIdProto>,
    #[prost(string, tag = "2")]
    pub producer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub producer_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub model_version: i64,
    #[prost(string, tag = "6")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub graph: ::core::option::Option<GraphProto>,
    #[prost(message, repeated, tag = "14")]
    pub metadata_props: ::prost::alloc::vec::Vec<StringStringEntryProto>,
    /// Using simplified type
    #[prost(message, repeated, tag = "20")]
    pub training_info: ::prost::alloc::vec::Vec<StringStringEntryProto>,
    #[prost(message, repeated, tag = "25")]
    pub functions: ::prost::alloc::vec::Vec<FunctionProto>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Version {
    StartVersion = 0,
    IrVersion20171010 = 1,
    IrVersion20171030 = 2,
    IrVersion2017113 = 3,
    IrVersion2019122 = 4,
    IrVersion2019318 = 5,
    IrVersion2019919 = 6,
    IrVersion202058 = 7,
    IrVersion2021730 = 8,
    IrVersion202355 = 9,
    IrVersion2024325 = 10,
    IrVersion20250512 = 11,
    IrVersion20250826 = 12,
    IrVersion = 13,
}
impl Version {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::StartVersion => "_START_VERSION",
            Self::IrVersion20171010 => "IR_VERSION_2017_10_10",
            Self::IrVersion20171030 => "IR_VERSION_2017_10_30",
            Self::IrVersion2017113 => "IR_VERSION_2017_11_3",
            Self::IrVersion2019122 => "IR_VERSION_2019_1_22",
            Self::IrVersion2019318 => "IR_VERSION_2019_3_18",
            Self::IrVersion2019919 => "IR_VERSION_2019_9_19",
            Self::IrVersion202058 => "IR_VERSION_2020_5_8",
            Self::IrVersion2021730 => "IR_VERSION_2021_7_30",
            Self::IrVersion202355 => "IR_VERSION_2023_5_5",
            Self::IrVersion2024325 => "IR_VERSION_2024_3_25",
            Self::IrVersion20250512 => "IR_VERSION_2025_05_12",
            Self::IrVersion20250826 => "IR_VERSION_2025_08_26",
            Self::IrVersion => "IR_VERSION",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "_START_VERSION" => Some(Self::StartVersion),
            "IR_VERSION_2017_10_10" => Some(Self::IrVersion20171010),
            "IR_VERSION_2017_10_30" => Some(Self::IrVersion20171030),
            "IR_VERSION_2017_11_3" => Some(Self::IrVersion2017113),
            "IR_VERSION_2019_1_22" => Some(Self::IrVersion2019122),
            "IR_VERSION_2019_3_18" => Some(Self::IrVersion2019318),
            "IR_VERSION_2019_9_19" => Some(Self::IrVersion2019919),
            "IR_VERSION_2020_5_8" => Some(Self::IrVersion202058),
            "IR_VERSION_2021_7_30" => Some(Self::IrVersion2021730),
            "IR_VERSION_2023_5_5" => Some(Self::IrVersion202355),
            "IR_VERSION_2024_3_25" => Some(Self::IrVersion2024325),
            "IR_VERSION_2025_05_12" => Some(Self::IrVersion20250512),
            "IR_VERSION_2025_08_26" => Some(Self::IrVersion20250826),
            "IR_VERSION" => Some(Self::IrVersion),
            _ => None,
        }
    }
}
